import { renderToStaticMarkup } from "react-dom/server";
import WelcomePage from "./WelcomePage";

export const WELCOME_TITLE = "e-SKY LAB · SKY LAB'in giriş hizmeti";
const WELCOME_DESCRIPTION =
  "e-SKY LAB, SKY LAB'in giriş hizmetidir: kulübün uygulamalarına ve sitelerine tek hesapla girersin.";

/**
 * The welcome theme's index.ftl, which Keycloak's WelcomeResource renders at `/`.
 *
 * Keycloak hands this template adminUrl, localAdminUrl, bootstrap and (on a fresh server, from
 * localhost) the admin creation form's stateChecker. The page uses only `resourcesPath`, for its
 * stylesheet and icon, so it can show neither the Admin Console link nor the form. The body sits
 * inside `<#noparse>`: FreeMarker copies it as it is, whatever the copy contains.
 */
export function renderWelcomeTemplate(): string {
  const body = renderToStaticMarkup(<WelcomePage />);

  return [
    "<#-- Generated by scripts/build-welcome-theme.mjs from src/welcome (WelcomePage.tsx, template.tsx); edit those. -->",
    "<!doctype html>",
    '<html lang="tr" class="sl-html">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="color-scheme" content="dark">',
    `<meta name="description" content="${WELCOME_DESCRIPTION}">`,
    `<title>${WELCOME_TITLE}</title>`,
    '<link rel="icon" type="image/png" href="${resourcesPath}/skylab-logo.png">',
    '<link rel="stylesheet" href="${resourcesPath}/welcome.css">',
    "</head>",
    '<body class="sl-body">',
    "<#noparse>",
    body,
    "</#noparse>",
    "</body>",
    "</html>",
    ""
  ].join("\n");
}
