#!/usr/bin/env bash
# Idempotent provisioning of Place's login client in the production realm (e-skylab), ADR-0060.
# Place's backend (api.place.yildizskylab.com) runs the e-skylab login itself as a confidential
# client (a BFF: authorization code + PKCE); Keycloak's tokens never reach the browser (ADR-0058),
# Place hands out its own session cookie. Place has no sandbox, so realm e-skylab is the only one.
# The script makes:
#   - the client place: confidential (the client secret is generated by Keycloak and never
#     printed), standard flow only (implicit flow, direct grants, service account, device grant,
#     CIBA and standard token exchange off), PKCE S256 required, fullScopeAllowed=false (tokens
#     carry Place's own roles only), consent off, front-channel logout off (a Place logout ends the
#     Place session only); redirect URI exactly https://api.place.yildizskylab.com/api/auth/eskylab/callback
#     and no web origin (the browser never calls Keycloak's endpoints). Other URIs on the client
#     are removed and listed;
#   - the client roles place:admin and place:moderator (ADR-0059: an application-wide permission
#     is a client role). Nothing is ever granted: people and groups get them in the SKY LAB admin
#     panel. Who holds them is reported (counts of people, group paths);
#   - the client mapper school-email: user attribute schoolEmail as the claim school_email in the
#     ID token, access token, userinfo and introspection. Place maps accounts by it; the person's
#     primary address (email, possibly personal, ADR-0044) is never used for that;
#   - the client mapper place-roles: the person's place roles as resource_access.place.roles in the
#     ID token, access token, userinfo and introspection (the realm's roles scope reaches the access
#     token only; Place validates the ID token);
#   - no groups (ADR-0059: Place reads no groups) and one source of school_email (the mapper
#     school-email). A default or optional client scope of the client that writes group data (a
#     Group Membership mapper, or any mapper whose claim is groups) or the claim school_email is
#     detached from the client, and from the client only: the realm scope, the realm's default
#     scopes and every other client keep it. Keycloak attaches the realm's default scopes to a new
#     client, among them microprofile-jwt, whose mapper "groups" writes the realm roles, and
#     profile, which in production carries a hand-made school_email mapper that core reads. Place
#     reads nothing from profile (only school_email, resource_access.place.roles, sub and the
#     standard ID token fields; it asks for the scope openid only). A detached scope stays detached:
#     a second run finds nothing to do.
# A mapper on the client itself that writes group data or school_email (other than school-email),
# or a mapper named school-email or place-roles of another type, is a PROBLEM (never changed). A
# User Profile that does not declare schoolEmail is a WARNING (reconcile-account-center.sh
# declares it).
#
# It refuses every realm but e-skylab, before it logs in. Without the realm it stops and writes
# nothing.
#
# Usage (inside the Keycloak image, as an operator):
#   create-place-client.sh --admin-user <admin>             # --check (default): state and plan
#   create-place-client.sh --admin-user <admin> --apply     # creates and repairs
#   create-place-client.sh --kcadm-config <file> [--apply]  # reuse a logged-in kcadm session
#
# The administrator password is typed into kcadm's own prompt and never passes through this
# script. --kcadm-config reuses a kcadm config file an operator (or the wizard) already logged in
# with; the script then never logs in and never deletes that file. Environment: KEYCLOAK_ADMIN_URL
# (default http://keycloak:8080), KEYCLOAK_REALM (default e-skylab, the only one accepted),
# KEYCLOAK_ADMIN_REALM (default master), KEYCLOAK_PLACE_CLIENT_ADMIN_USERNAME (or --admin-user).
#
# Output: one "[place-client] ..." line per fact, change ("would ..." in --check), NOTE, WARNING
# and PROBLEM, then "check: N change(s) pending, W warning(s), P problem(s)" or "applied N
# change(s), ...". Exit 0 unless a PROBLEM or a missing realm (1) or a usage error or a refused
# realm (2). No secret or token is ever read or printed.
# Operators: ops/wizards/place-keycloak-client-wizard.sh in sky_lab_genel runs it in production and
# moves the client secret into OpenBao (kv/etkinlik/<Place appName>/KEYCLOAK_CLIENT_SECRET).
set -Eeuo pipefail
shopt -s inherit_errexit

umask 077

KCADM=${KCADM_BIN:-/opt/keycloak/bin/kcadm.sh}
ADMIN_URL=${KEYCLOAK_ADMIN_URL:-http://keycloak:8080}
ADMIN_REALM=${KEYCLOAK_ADMIN_REALM:-master}
PRODUCTION_REALM=e-skylab
TARGET_REALM=${KEYCLOAK_REALM:-$PRODUCTION_REALM}
ADMIN_USER=${KEYCLOAK_PLACE_CLIENT_ADMIN_USERNAME:-}
KCADM_CONFIG=''
OWN_CONFIG=false
MODE=check

CLIENT_ID=place
CLIENT_NAME=Place
CLIENT_DESCRIPTION='api.place.yildizskylab.com: Place backend (BFF) e-skylab login, ADR-0060. Made by config/create-place-client.sh'
REDIRECT_URI=https://api.place.yildizskylab.com/api/auth/eskylab/callback
FLAG_FIELDS='enabled,protocol,publicClient,bearerOnly,clientAuthenticatorType,standardFlowEnabled,implicitFlowEnabled,directAccessGrantsEnabled,serviceAccountsEnabled,fullScopeAllowed,consentRequired,frontchannelLogout,attributes(pkce.code.challenge.method,oauth2.device.authorization.grant.enabled,oidc.ciba.grant.enabled,standard.token.exchange.enabled)'
FLAG_VALUES='true,openid-connect,false,false,client-secret,true,false,false,false,false,false,false,S256,false,false,false'
FLAG_SETTINGS=(
  -s enabled=true
  -s protocol=openid-connect
  -s publicClient=false
  -s bearerOnly=false
  -s clientAuthenticatorType=client-secret
  -s standardFlowEnabled=true
  -s implicitFlowEnabled=false
  -s directAccessGrantsEnabled=false
  -s serviceAccountsEnabled=false
  -s fullScopeAllowed=false
  -s consentRequired=false
  -s frontchannelLogout=false
  -s 'attributes."pkce.code.challenge.method"=S256'
  -s 'attributes."oauth2.device.authorization.grant.enabled"=false'
  -s 'attributes."oidc.ciba.grant.enabled"=false'
  -s 'attributes."standard.token.exchange.enabled"=false'
)
ROLES=(place:admin place:moderator)
declare -A ROLE_DESCRIPTION=(
  [place:admin]='Place: administrator (admin endpoints). Read by the Place backend from resource_access.place.roles at an e-skylab login (ADR-0060). Granted in the SKY LAB admin panel'
  [place:moderator]='Place: moderator (moderation endpoints). Read by the Place backend from resource_access.place.roles at an e-skylab login (ADR-0060). Granted in the SKY LAB admin panel'
)
SCHOOL_MAPPER=school-email
SCHOOL_ATTRIBUTE=schoolEmail
SCHOOL_CLAIM=school_email
ROLES_MAPPER=place-roles
# shellcheck disable=SC2016  # ${client_id} is Keycloak's placeholder, not a shell variable
ROLES_CLAIM='resource_access.${client_id}.roles'
GROUPS_CLAIM=groups
# Mapper CSV: the free-text name last, so a comma in it cannot shift the other columns.
MAPPER_FIELDS='id,protocolMapper,config(claim.name,user.attribute,usermodel.clientRoleMapping.clientId,multivalued,jsonType.label,id.token.claim,access.token.claim,userinfo.token.claim,introspection.token.claim),name'
# The columns after id and before the name, as the own mappers must read (see mapper_line).
SCHOOL_SHAPE="oidc-usermodel-attribute-mapper,$SCHOOL_CLAIM,$SCHOOL_ATTRIBUTE,,false,String,true,true,true,true"
ROLES_SHAPE="oidc-usermodel-client-role-mapper,$ROLES_CLAIM,,$CLIENT_ID,true,String,true,true,true,true"

usage() {
  printf 'usage: %s (--admin-user <administrator> | --kcadm-config <file>) [--check | --apply]\n' \
    "${BASH_SOURCE[0]##*/}" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --admin-user)
      [[ $# -ge 2 ]] || usage
      ADMIN_USER=$2
      shift 2
      ;;
    --kcadm-config)
      [[ $# -ge 2 ]] || usage
      KCADM_CONFIG=$2
      shift 2
      ;;
    --apply)
      MODE=apply
      shift
      ;;
    --check | --dry-run)
      MODE=check
      shift
      ;;
    *)
      usage
      ;;
  esac
done

# Before anything else, and before a login: Place lives in the production realm only.
if [[ $TARGET_REALM != "$PRODUCTION_REALM" ]]; then
  printf '[place-client] refusing realm %s: Place has no sandbox, this script writes only the realm %s; nothing was read or changed\n' \
    "$TARGET_REALM" "$PRODUCTION_REALM" >&2
  exit 2
fi

if [[ -z $KCADM_CONFIG ]]; then
  if [[ -z $ADMIN_USER ]]; then
    if [[ -t 0 ]]; then
      read -r -p "Keycloak administrator username: " ADMIN_USER
    fi
    [[ -n $ADMIN_USER ]] || usage
  fi
  KCADM_CONFIG=$(mktemp /tmp/place-client-kcadm.XXXXXX)
  OWN_CONFIG=true
elif [[ ! -r $KCADM_CONFIG ]]; then
  printf 'kcadm config %s is not readable\n' "$KCADM_CONFIG" >&2
  exit 2
fi

cleanup() {
  if [[ $OWN_CONFIG == true ]]; then
    rm -f "$KCADM_CONFIG"
  fi
}
trap cleanup EXIT

log() {
  printf '[place-client] %s\n' "$1"
}

changes=0
warnings=0
problems=0

# change "what": counts one change and prints it; --check prints "would what".
change() {
  changes=$((changes + 1))
  if [[ $MODE == apply ]]; then
    log "$1"
  else
    log "would $1"
  fi
}

warning() {
  warnings=$((warnings + 1))
  log "WARNING: $1"
}

problem() {
  problems=$((problems + 1))
  log "PROBLEM: $1"
}

kcadm() {
  local command=$1
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

kcadm_write() {
  local stderr_file status
  stderr_file=$(mktemp /tmp/place-client-stderr.XXXXXX)
  if kcadm "$@" >/dev/null 2>"$stderr_file"; then
    status=0
  else
    status=$?
    cat "$stderr_file" >&2
  fi
  rm -f "$stderr_file"
  return "$status"
}

# csv PATH FIELDS [kcadm arguments]: the CSV lines of a GET in the target realm (no quotes,
# empty lines dropped).
csv() {
  kcadm get "$1" -r "$TARGET_REALM" --fields "$2" --format csv --noquotes "${@:3}" | tr -d '\r' | sed '/^$/d'
}

# json_strings ITEM...: a JSON array of plain strings (URIs; a quote or backslash is refused).
json_strings() {
  local out='' item
  for item in "$@"; do
    [[ $item != *[\"\\]* ]] || { printf 'refusing to write the value %s\n' "$item" >&2; exit 1; }
    out+="${out:+,}\"$item\""
  done
  printf '[%s]' "$out"
}

# uuid_by CLIENT_ID: the id of the client with exactly this clientId (empty when absent).
uuid_by() {
  csv clients id,clientId -q "clientId=$1" | while IFS=, read -r id client_id; do
    if [[ $client_id == "$1" ]]; then printf '%s\n' "$id"; fi
  done
}

# list_items PATH FIELD: the entries of a client's list field (redirectUris, webOrigins), one per
# line (kcadm joins them with commas; a URI with a comma would split, none of ours has one).
list_items() {
  csv "$1" "$2" | tr ',' '\n' | sed '/^$/d'
}

# The mapper bodies this script writes.
school_mapper_body() { # school_mapper_body [ID]
  local id_field=''
  [[ -z ${1:-} ]] || id_field="\"id\":\"$1\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-usermodel-attribute-mapper","consentRequired":false,"config":{"user.attribute":"%s","claim.name":"%s","jsonType.label":"String","multivalued":"false","aggregate.attrs":"false","id.token.claim":"true","access.token.claim":"true","userinfo.token.claim":"true","introspection.token.claim":"true","lightweight.claim":"false"}}' \
    "$id_field" "$SCHOOL_MAPPER" "$SCHOOL_ATTRIBUTE" "$SCHOOL_CLAIM"
}
roles_mapper_body() { # roles_mapper_body [ID]
  local id_field=''
  [[ -z ${1:-} ]] || id_field="\"id\":\"$1\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-usermodel-client-role-mapper","consentRequired":false,"config":{"usermodel.clientRoleMapping.clientId":"%s","claim.name":"%s","jsonType.label":"String","multivalued":"true","id.token.claim":"true","access.token.claim":"true","userinfo.token.claim":"true","introspection.token.claim":"true","lightweight.claim":"false"}}' \
    "$id_field" "$ROLES_MAPPER" "$CLIENT_ID" "$ROLES_CLAIM"
}

# mapper_line LINE: the columns between the id and the name (type, claim, attribute, role client,
# multivalued, JSON type, ID token, access token, userinfo, introspection).
mapper_line() {
  local rest=${1#*,}
  printf '%s' "${rest%,*}"
}
# writes_groups SHAPE: the mapper puts group data into a token: a Group Membership mapper, or any
# mapper whose claim is groups (microprofile-jwt's "groups" writes the realm roles under it).
writes_groups() {
  local type claim rest
  IFS=, read -r type claim rest <<<"$1"
  [[ $type == oidc-group-membership-mapper || $claim == "$GROUPS_CLAIM" || $claim == "$GROUPS_CLAIM".* ]]
}
# writes_school SHAPE: the mapper writes the claim school_email.
writes_school() {
  local type claim rest
  IFS=, read -r type claim rest <<<"$1"
  [[ $claim == "$SCHOOL_CLAIM" ]]
}

credential_arguments=(
  --config "$KCADM_CONFIG"
  --server "$ADMIN_URL"
  --realm "$ADMIN_REALM"
  --user "$ADMIN_USER"
)
if [[ $OWN_CONFIG == true ]]; then
  # No redirection: kcadm asks for the password only when stdout is a terminal ("Console is not
  # active" otherwise). Its "Logging into" line goes to stderr, so stdout stays clean either way.
  "$KCADM" config credentials "${credential_arguments[@]}"
fi
log "realm=$TARGET_REALM mode=$MODE client=$CLIENT_ID"

# --- prerequisites: nothing is written unless they hold ------------------------------------------
if ! realm_name=$(kcadm get "realms/$TARGET_REALM" --fields realm --format csv --noquotes 2>/dev/null | tr -d '\r') \
  || [[ $realm_name != "$TARGET_REALM" ]]; then
  printf '[place-client] realm %s does not exist or cannot be read; nothing was changed\n' "$TARGET_REALM" >&2
  exit 1
fi
if kcadm get users/profile -r "$TARGET_REALM" 2>/dev/null | grep -Eq "\"name\" *: *\"$SCHOOL_ATTRIBUTE\""; then
  log "User Profile declares $SCHOOL_ATTRIBUTE"
else
  warning "the User Profile of realm $TARGET_REALM does not declare $SCHOOL_ATTRIBUTE; tokens carry no $SCHOOL_CLAIM until it does (reconcile-account-center.sh declares it)"
fi

# --- 1. the client ------------------------------------------------------------------------------
client_uuid=$(uuid_by "$CLIENT_ID")
created=false
if [[ -z $client_uuid ]]; then
  change "create confidential client $CLIENT_ID (standard flow only, PKCE S256, fullScopeAllowed=false, front-channel logout off; redirect $REDIRECT_URI, no web origin; the secret is generated by Keycloak and never printed)"
  if [[ $MODE == apply ]]; then
    client_uuid=$(kcadm create clients -r "$TARGET_REALM" -i \
      -s "clientId=$CLIENT_ID" \
      -s "name=$CLIENT_NAME" \
      -s "description=$CLIENT_DESCRIPTION" \
      "${FLAG_SETTINGS[@]}" \
      -s "redirectUris=$(json_strings "$REDIRECT_URI")" \
      -s 'webOrigins=[]' | tr -d '\r')
    [[ -n $client_uuid ]] || { printf 'client %s was not created\n' "$CLIENT_ID" >&2; exit 1; }
    created=true
  fi
else
  live_flags=$(csv "clients/$client_uuid" "$FLAG_FIELDS")
  if [[ $live_flags == "$FLAG_VALUES" ]]; then
    log "$CLIENT_ID: flags unchanged ($FLAG_FIELDS=$live_flags)"
  else
    change "update $CLIENT_ID flags ($FLAG_FIELDS: $live_flags -> $FLAG_VALUES)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" "${FLAG_SETTINGS[@]}"
    fi
  fi

  # The redirect URI is the only one; the browser never calls Keycloak's endpoints (no origin).
  redirects=$(list_items "clients/$client_uuid" redirectUris)
  if [[ $redirects == "$REDIRECT_URI" ]]; then
    log "$CLIENT_ID: redirect URI exactly $REDIRECT_URI"
  else
    others=$(grep -Fxv -- "$REDIRECT_URI" <<<"$redirects" | paste -sd' ' - || true)
    change "set the redirect URIs of $CLIENT_ID to exactly $REDIRECT_URI${others:+ (removing $others)}"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" -s "redirectUris=$(json_strings "$REDIRECT_URI")"
    fi
  fi
  origins=$(list_items "clients/$client_uuid" webOrigins | paste -sd' ' - || true)
  if [[ -z $origins ]]; then
    log "$CLIENT_ID: no web origin"
  else
    change "remove the web origins of $CLIENT_ID ($origins)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" -s 'webOrigins=[]'
    fi
  fi
fi
[[ $created == false ]] || log "$CLIENT_ID: created (id $client_uuid; the secret is never printed: ops/wizards/place-keycloak-client-wizard.sh moves it into OpenBao)"

# --- 2. the roles (never granted here) -----------------------------------------------------------
declare -A role_exists=()
if [[ -n $client_uuid ]]; then
  while IFS=, read -r role_id role_name; do
    [[ -z $role_id ]] || role_exists[$role_name]=1
  done < <(csv "clients/$client_uuid/roles" id,name)
fi
for role in "${ROLES[@]}"; do
  if [[ -n ${role_exists[$role]:-} ]]; then
    log "$CLIENT_ID: role $role exists"
    continue
  fi
  change "create client role $role on $CLIENT_ID"
  if [[ $MODE == apply ]]; then
    kcadm_write create "clients/$client_uuid/roles" -r "$TARGET_REALM" \
      -s "name=$role" -s "description=${ROLE_DESCRIPTION[$role]}"
    role_exists[$role]=1
  fi
done

# --- 3. what reaches the tokens: the client's mappers and its scopes -----------------------------
# A client still to be made (--check) would get the realm's default and optional OpenID Connect
# scopes; Keycloak attaches them on creation.
client_mappers=''
# shellcheck disable=SC2034  # optional_scope_by_name is read through check_scopes' nameref
declare -A default_scope_by_name=() optional_scope_by_name=()
if [[ -n $client_uuid ]]; then
  client_mappers=$(csv "clients/$client_uuid/protocol-mappers/models" "$MAPPER_FIELDS")
  while IFS=, read -r scope_id scope_name; do
    if [[ -n $scope_id ]]; then default_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv "clients/$client_uuid/default-client-scopes" id,name)
  while IFS=, read -r scope_id scope_name; do
    if [[ -n $scope_id ]]; then optional_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv "clients/$client_uuid/optional-client-scopes" id,name)
else
  while IFS=, read -r scope_id scope_name scope_protocol; do
    if [[ -n $scope_id && $scope_protocol == openid-connect ]]; then default_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv default-default-client-scopes id,name,protocol)
  while IFS=, read -r scope_id scope_name scope_protocol; do
    if [[ -n $scope_id && $scope_protocol == openid-connect ]]; then optional_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv default-optional-client-scopes id,name,protocol)
fi

# --- 3a. the client's own mappers ----------------------------------------------------------------
own_school_line=''
own_roles_line=''
while IFS= read -r line; do
  [[ -n $line ]] || continue
  name=${line##*,}
  shape=$(mapper_line "$line")
  type=${shape%%,*}
  if [[ $name == "$SCHOOL_MAPPER" && $type == oidc-usermodel-attribute-mapper ]]; then
    own_school_line=$line
    continue
  fi
  if [[ $name == "$ROLES_MAPPER" && $type == oidc-usermodel-client-role-mapper ]]; then
    own_roles_line=$line
    continue
  fi
  if [[ $name == "$SCHOOL_MAPPER" || $name == "$ROLES_MAPPER" ]]; then
    problem "$CLIENT_ID has a mapper named $name of type $type; rename or remove it by hand"
  fi
  if writes_groups "$shape"; then
    problem "$CLIENT_ID: client mapper $name ($type) writes group data; Place reads no groups (ADR-0059). Remove it by hand"
  fi
  if writes_school "$shape"; then
    problem "$CLIENT_ID: client mapper $name ($type) also writes $SCHOOL_CLAIM; remove it by hand"
  fi
done <<<"$client_mappers"

# ensure_own_mapper NAME LINE SHAPE BODY_FUNCTION DESCRIPTION: the own mapper, made or repaired.
ensure_own_mapper() {
  local name=$1 line=$2 want=$3 body=$4 what=$5 id
  if [[ -z $line ]]; then
    change "add mapper $name to $CLIENT_ID ($what)"
    if [[ $MODE == apply ]]; then
      kcadm_write create "clients/$client_uuid/protocol-mappers/models" -r "$TARGET_REALM" -b "$("$body")"
    fi
    return 0
  fi
  if [[ $(mapper_line "$line") == "$want" ]]; then
    log "$CLIENT_ID: mapper $name unchanged ($what)"
    return 0
  fi
  id=${line%%,*}
  change "repair mapper $name on $CLIENT_ID ($(mapper_line "$line") -> $want)"
  if [[ $MODE == apply ]]; then
    kcadm_write update "clients/$client_uuid/protocol-mappers/models/$id" -r "$TARGET_REALM" -b "$("$body" "$id")"
  fi
}
ensure_own_mapper "$SCHOOL_MAPPER" "$own_school_line" "$SCHOOL_SHAPE" school_mapper_body \
  "user attribute $SCHOOL_ATTRIBUTE -> $SCHOOL_CLAIM; ID token, access token, userinfo, introspection"
ensure_own_mapper "$ROLES_MAPPER" "$own_roles_line" "$ROLES_SHAPE" roles_mapper_body \
  "$CLIENT_ID roles -> resource_access.$CLIENT_ID.roles; ID token, access token, userinfo, introspection"

# --- 3b. the client's scopes: none may write group data or school_email --------------------------
# One read of every client scope of the realm: its id, then (mapper type, claim) pairs.
declare -A scope_groups=() scope_school=()
while IFS= read -r line; do
  [[ -n $line ]] || continue
  IFS=, read -r -a cells <<<"$line"
  for ((i = 1; i < ${#cells[@]}; i += 2)); do
    pair="${cells[i]},${cells[i + 1]:-}"
    if writes_groups "$pair"; then
      scope_groups[${cells[0]}]+="${scope_groups[${cells[0]}]:+, }${cells[i + 1]:-?} (${cells[i]})"
    fi
    if writes_school "$pair"; then
      scope_school[${cells[0]}]+="${scope_school[${cells[0]}]:+, }${cells[i]}"
    fi
  done
done < <(csv client-scopes 'id,protocolMappers(protocolMapper,config(claim.name))')

# check_scopes KIND: KIND is default or optional. Detaches from the client every such scope that
# writes group data or school_email. Only the client's link to the scope is deleted
# (clients/<place>/<kind>-client-scopes/<scope>); the scope, the realm's default scopes and the
# other clients are never written.
detached=0
check_scopes() {
  local kind=$1 scope_name scope_id groups school reasons
  local -n scopes=${kind}_scope_by_name
  while IFS= read -r scope_name; do
    [[ -n $scope_name ]] || continue
    scope_id=${scopes[$scope_name]}
    groups=${scope_groups[$scope_id]:-}
    school=${scope_school[$scope_id]:-}
    if [[ -z $groups && -z $school ]]; then
      continue
    fi
    reasons=''
    [[ -z $groups ]] || reasons="it writes group data: $groups; ADR-0059"
    [[ -z $school ]] || reasons+="${reasons:+; }it writes $SCHOOL_CLAIM ($school), which only the mapper $SCHOOL_MAPPER on $CLIENT_ID may write; the scope itself and other clients are not changed"
    detached=$((detached + 1))
    change "detach the $kind scope $scope_name from $CLIENT_ID ($reasons)"
    if [[ $MODE == apply ]]; then
      kcadm_write delete "clients/$client_uuid/$kind-client-scopes/$scope_id" -r "$TARGET_REALM"
    fi
  done < <(printf '%s\n' "${!scopes[@]}" | sort)
}
check_scopes default
check_scopes optional
if [[ $detached == 0 ]]; then
  log "$CLIENT_ID: no default or optional scope writes group data or $SCHOOL_CLAIM (default: $(printf '%s\n' "${!default_scope_by_name[@]}" | sort | paste -sd' ' -))"
fi

# --- 4. who holds the roles (read-only) ----------------------------------------------------------
if [[ -n $client_uuid && $created == false ]]; then
  for role in "${ROLES[@]}"; do
    [[ -n ${role_exists[$role]:-} ]] || continue
    people=$(csv "clients/$client_uuid/roles/$role/users" id -q briefRepresentation=true -q max=1000 2>/dev/null | wc -l | tr -d ' ' || true)
    groups=$(csv "clients/$client_uuid/roles/$role/groups" path -q briefRepresentation=true 2>/dev/null | paste -sd' ' - || true)
    log "$CLIENT_ID: role $role held directly by ${people:-?} person(s); groups: ${groups:-none}"
  done
fi

log "next: the Place backend reads issuer https://e.yildizskylab.com/realms/$TARGET_REALM, client $CLIENT_ID, redirect $REDIRECT_URI; the secret goes to OpenBao with the wizard, never by hand"
if [[ $MODE == apply ]]; then
  log "applied $changes change(s), $warnings warning(s), $problems problem(s)"
else
  log "check: $changes change(s) pending, $warnings warning(s), $problems problem(s)"
fi
if [[ $problems != 0 ]]; then
  log "$problems problem(s) need a manual decision (see PROBLEM lines above)"
  exit 1
fi
