#!/usr/bin/env bash
# One-off, idempotent provisioning of the keycloak-mailer service-account client (K5): the
# confidential client, its roles default scope and the SkyMail client roles on its service
# account. The steady-state reconciler only verifies this client because assigning user
# roles needs user permissions the reconciler identity deliberately does not have.
#
# Usage (inside the Keycloak image, as an operator):
#   create-mailer-client.sh --admin-user <admin>            # dry run (default): prints the plan
#   create-mailer-client.sh --admin-user <admin> --apply    # creates, updates and assigns
#
# The administrator password is typed into kcadm's own prompt and never passes through this
# script. Environment: KEYCLOAK_ADMIN_URL (default http://keycloak:8080), KEYCLOAK_REALM
# (default e-skylab), KEYCLOAK_ADMIN_REALM (default master). KEYCLOAK_MAILER_ADMIN_PASSWORD
# is accepted only together with SKY_HARNESS=1 (the integration harness); anywhere else the
# script refuses it, because kcadm would receive the password on its command line.
#
# The client secret is generated by Keycloak and never printed. Read it once, with shell
# history and terminal recording disabled:
#   kcadm.sh get clients/<client-uuid>/client-secret -r e-skylab
set -Eeuo pipefail
shopt -s inherit_errexit

umask 077

KCADM=${KCADM_BIN:-/opt/keycloak/bin/kcadm.sh}
CONFIG_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ADMIN_URL=${KEYCLOAK_ADMIN_URL:-http://keycloak:8080}
ADMIN_REALM=${KEYCLOAK_ADMIN_REALM:-master}
TARGET_REALM=${KEYCLOAK_REALM:-e-skylab}
ADMIN_USER=${KEYCLOAK_MAILER_ADMIN_USERNAME:-}
KCADM_CONFIG=$(mktemp /tmp/mailer-client-kcadm.XXXXXX)
MODE=dry-run

# shellcheck source=mailer-client-contract.sh
source "$CONFIG_DIR/mailer-client-contract.sh"

cleanup() {
  rm -f "$KCADM_CONFIG"
}
trap cleanup EXIT

usage() {
  printf 'usage: %s --admin-user <administrator> [--apply]\n' "${BASH_SOURCE[0]##*/}" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --admin-user)
      [[ $# -ge 2 ]] || usage
      ADMIN_USER=$2
      shift 2
      ;;
    --apply)
      MODE=apply
      shift
      ;;
    --dry-run)
      MODE=dry-run
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [[ -z $ADMIN_USER ]]; then
  if [[ -t 0 ]]; then
    read -r -p "Keycloak administrator username: " ADMIN_USER
  fi
  [[ -n $ADMIN_USER ]] || usage
fi

log() {
  printf '[mailer-client] %s\n' "$1"
}

plan() {
  if [[ $MODE == apply ]]; then
    log "$1"
  else
    log "would $1"
  fi
}

kcadm() {
  local command=$1
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

kcadm_write() {
  local stderr_file status
  stderr_file=$(mktemp /tmp/mailer-client-stderr.XXXXXX)
  if kcadm "$@" >/dev/null 2>"$stderr_file"; then
    status=0
  else
    status=$?
    cat "$stderr_file" >&2
  fi
  rm -f "$stderr_file"
  return "$status"
}

client_uuid_by_client_id() {
  local wanted=$1 clients_csv id client_id
  clients_csv=$(kcadm get clients -r "$TARGET_REALM" -q "clientId=$wanted" \
    --fields id,clientId \
    --format csv \
    --noquotes)
  while IFS=, read -r id client_id; do
    if [[ $client_id == "$wanted" ]]; then
      printf '%s\n' "$id"
      return 0
    fi
  done <<<"$clients_csv"
  return 1
}

role_id_by_name() {
  local client_uuid=$1 wanted=$2 roles_csv id name
  roles_csv=$(kcadm get "clients/$client_uuid/roles" -r "$TARGET_REALM" \
    --fields id,name \
    --format csv \
    --noquotes)
  while IFS=, read -r id name; do
    if [[ $name == "$wanted" ]]; then
      printf '%s\n' "$id"
      return 0
    fi
  done <<<"$roles_csv"
  return 1
}

credential_arguments=(
  --config "$KCADM_CONFIG"
  --server "$ADMIN_URL"
  --realm "$ADMIN_REALM"
  --user "$ADMIN_USER"
)
if [[ -n ${KEYCLOAK_MAILER_ADMIN_PASSWORD:-} ]]; then
  if [[ ${SKY_HARNESS:-} != 1 ]]; then
    printf 'KEYCLOAK_MAILER_ADMIN_PASSWORD is accepted only by the test harness (SKY_HARNESS=1); unset it and type the password into the kcadm prompt\n' >&2
    exit 2
  fi
  credential_arguments+=(--password "$KEYCLOAK_MAILER_ADMIN_PASSWORD")
fi
"$KCADM" config credentials "${credential_arguments[@]}" >/dev/null
log "realm=$TARGET_REALM client=$MAILER_CLIENT_ID mode=$MODE"

changes=0

# --- client -----------------------------------------------------------------------------
if mailer_uuid=$(client_uuid_by_client_id "$MAILER_CLIENT_ID"); then
  live_flags=$(mailer_client_flags "$mailer_uuid" 2>/dev/null)
  if [[ $live_flags == "$MAILER_FLAG_VALUES" ]]; then
    log "client $MAILER_CLIENT_ID: flags unchanged"
  else
    plan "update client $MAILER_CLIENT_ID flags ($MAILER_FLAG_FIELDS: $live_flags -> $MAILER_FLAG_VALUES)"
    changes=$((changes + 1))
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$mailer_uuid" -r "$TARGET_REALM" \
        -s "name=$MAILER_CLIENT_NAME" \
        -s "description=$MAILER_CLIENT_DESCRIPTION" \
        "${MAILER_FLAG_SETTINGS[@]}"
    fi
  fi
else
  plan "create confidential service-account client $MAILER_CLIENT_ID (secret generated by Keycloak)"
  changes=$((changes + 1))
  if [[ $MODE == apply ]]; then
    mailer_uuid=$(kcadm create clients -r "$TARGET_REALM" -i \
      -s "clientId=$MAILER_CLIENT_ID" \
      -s "name=$MAILER_CLIENT_NAME" \
      -s "description=$MAILER_CLIENT_DESCRIPTION" \
      -s protocol=openid-connect \
      "${MAILER_FLAG_SETTINGS[@]}")
    log "client $MAILER_CLIENT_ID: created (read the secret with kcadm get clients/$mailer_uuid/client-secret -r $TARGET_REALM)"
  else
    mailer_uuid=''
  fi
fi

# --- roles default scope -----------------------------------------------------------------
# SkyMail reads resource_access.skymail.roles from the token; the realm's roles scope emits it.
# In a dry run of a missing client every later step is planned against the empty client so the
# pending count covers the whole provisioning.
if [[ -n $mailer_uuid ]] && [[ -n $(mailer_roles_scope_attached "$mailer_uuid" 2>/dev/null) ]]; then
  log "client $MAILER_CLIENT_ID: roles default scope attached"
else
  roles_scope_uuid=$(kcadm get client-scopes -r "$TARGET_REALM" \
    --fields id,name \
    --format csv \
    --noquotes | grep -E ',roles$' | cut -d, -f1 | head -n 1)
  if [[ -z $roles_scope_uuid ]]; then
    log "WARNING: client scope roles does not exist; tokens of $MAILER_CLIENT_ID will not carry resource_access"
  else
    plan "attach the roles default scope to $MAILER_CLIENT_ID"
    changes=$((changes + 1))
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$mailer_uuid/default-client-scopes/$roles_scope_uuid" \
        -r "$TARGET_REALM" -n -b '{}'
    fi
  fi
fi

# --- SkyMail roles on the service account --------------------------------------------------
# The roles belong to SkyMail; they are assigned when they exist and reported when missing.
if ! skymail_uuid=$(client_uuid_by_client_id "$SKYMAIL_CLIENT_ID"); then
  log "WARNING: client $SKYMAIL_CLIENT_ID does not exist in realm $TARGET_REALM; no SkyMail roles were assigned"
  skymail_uuid=''
fi
if [[ -n $skymail_uuid ]]; then
  if [[ -n $mailer_uuid ]]; then
    service_user_id=$(kcadm get "clients/$mailer_uuid/service-account-user" -r "$TARGET_REALM" \
      --fields id \
      --format csv \
      --noquotes)
    [[ -n $service_user_id && $service_user_id != *,* ]] || {
      printf 'The %s service-account user could not be resolved exactly\n' "$MAILER_CLIENT_ID" >&2
      exit 1
    }
    assigned_csv=$(kcadm get "users/$service_user_id/role-mappings/clients/$skymail_uuid" \
      -r "$TARGET_REALM" --fields id,name --format csv --noquotes)
    scope_csv=$(kcadm get "clients/$mailer_uuid/scope-mappings/clients/$skymail_uuid" \
      -r "$TARGET_REALM" --fields id,name --format csv --noquotes)
  else
    # Dry run of a missing client: nothing is assigned yet, everything wanted is pending.
    service_user_id=''
    assigned_csv=''
    scope_csv=''
  fi
  missing=''
  while IFS=, read -r role_id role_name; do
    [[ -n $role_id ]] || continue
    keep=false
    for wanted in "${MAILER_SKYMAIL_ROLES[@]}"; do
      [[ $role_name == "$wanted" ]] && keep=true
    done
    if [[ $keep == false ]]; then
      plan "remove role $role_name from the $MAILER_CLIENT_ID service account"
      changes=$((changes + 1))
      if [[ $MODE == apply ]]; then
        kcadm_write delete "users/$service_user_id/role-mappings/clients/$skymail_uuid" \
          -r "$TARGET_REALM" -b "[{\"id\":\"$role_id\",\"name\":\"$role_name\"}]"
      fi
    fi
  done <<<"$assigned_csv"
  while IFS=, read -r role_id role_name; do
    [[ -n $role_id ]] || continue
    keep=false
    for wanted in "${MAILER_SKYMAIL_ROLES[@]}"; do
      [[ $role_name == "$wanted" ]] && keep=true
    done
    if [[ $keep == false ]]; then
      plan "remove scope mapping $role_name from $MAILER_CLIENT_ID"
      changes=$((changes + 1))
      if [[ $MODE == apply ]]; then
        kcadm_write delete "clients/$mailer_uuid/scope-mappings/clients/$skymail_uuid" \
          -r "$TARGET_REALM" -b "[{\"id\":\"$role_id\",\"name\":\"$role_name\"}]"
      fi
    fi
  done <<<"$scope_csv"
  for role_name in "${MAILER_SKYMAIL_ROLES[@]}"; do
    if ! role_id=$(role_id_by_name "$skymail_uuid" "$role_name"); then
      missing="$missing $role_name"
      continue
    fi
    if ! grep -Eq "^[^,]+,$role_name$" <<<"$assigned_csv"; then
      plan "assign role $role_name to the $MAILER_CLIENT_ID service account"
      changes=$((changes + 1))
      if [[ $MODE == apply ]]; then
        kcadm_write create "users/$service_user_id/role-mappings/clients/$skymail_uuid" \
          -r "$TARGET_REALM" -b "[{\"id\":\"$role_id\",\"name\":\"$role_name\"}]"
      fi
    fi
    if ! grep -Eq "^[^,]+,$role_name$" <<<"$scope_csv"; then
      plan "add scope mapping $role_name to $MAILER_CLIENT_ID"
      changes=$((changes + 1))
      if [[ $MODE == apply ]]; then
        kcadm_write create "clients/$mailer_uuid/scope-mappings/clients/$skymail_uuid" \
          -r "$TARGET_REALM" -b "[{\"id\":\"$role_id\",\"name\":\"$role_name\"}]"
      fi
    fi
  done
  if [[ -n $missing ]]; then
    log "WARNING: client $SKYMAIL_CLIENT_ID lacks the roles${missing}; SkyMail must create them, then rerun this script"
  fi
fi

if [[ $MODE == apply ]]; then
  log "applied $changes change(s); the reconciler now verifies $MAILER_CLIENT_ID on every run"
else
  log "dry run: $changes change(s) pending; rerun with --apply to execute them"
fi
