#!/usr/bin/env bash
# One-off, idempotent provisioning of the core-erasure service-account client (account erasure,
# ADR-0051, ticket 03). core sends SkyMail, CMS and Forms an Account erasure command each; the
# token for one service must not carry another service's erase role. In this order it
#   1. requires the resource clients skymail, skycms and forms and the scopes basic and roles;
#      when one is missing it stops and writes nothing;
#   2. creates the erase roles skymail:account:erase (skymail), cms:account:erase (skycms) and
#      skyforms:account:erase (forms) when they are missing;
#   3. keeps the optional client scopes account-erase-skymail, account-erase-cms and
#      account-erase-forms at exactly one audience mapper (aud = the resource client) and one
#      role scope mapping (that service's erase role, nothing else);
#   4. creates or repairs the confidential client core-erasure: service account only (standard,
#      implicit and direct grants off), fullScopeAllowed=false, default scopes exactly basic and
#      roles (plus service_account, which Keycloak manages), optional scopes exactly the three
#      erase scopes, no direct scope mappings;
#   5. gives service-account-core-erasure exactly the three erase roles of these clients;
#   6. reports (never removes) anyone else who holds an erase role directly or through a group.
# The reconciler only verifies this client: assigning roles to the service account needs user
# permissions the reconciler identity deliberately does not have.
#
# Usage (inside the Keycloak image, as an operator):
#   create-erasure-client.sh --admin-user <admin>            # dry run (default): prints the plan
#   create-erasure-client.sh --admin-user <admin> --apply    # creates, updates and assigns
#
# The administrator password is typed into kcadm's own prompt and never passes through this
# script. Environment: KEYCLOAK_ADMIN_URL (default http://keycloak:8080), KEYCLOAK_REALM
# (default e-skylab), KEYCLOAK_ADMIN_REALM (default master), KEYCLOAK_ERASURE_ADMIN_USERNAME (or
# --admin-user). KEYCLOAK_ERASURE_ADMIN_PASSWORD is accepted only together with SKY_HARNESS=1
# (the integration harness); anywhere else the script refuses it, because kcadm would receive
# the password on its command line.
#
# The client secret is generated by Keycloak and never printed. It reaches core only through
# OpenBao: ops/wizards/core-erasure-client-wizard.sh reads it with the admin API, writes it to
# kv/<side>/<core appName>/ACCOUNT_ERASURE_CLIENT_SECRET and references it in core's environment.
set -Eeuo pipefail
shopt -s inherit_errexit

umask 077

KCADM=${KCADM_BIN:-/opt/keycloak/bin/kcadm.sh}
CONFIG_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ADMIN_URL=${KEYCLOAK_ADMIN_URL:-http://keycloak:8080}
ADMIN_REALM=${KEYCLOAK_ADMIN_REALM:-master}
TARGET_REALM=${KEYCLOAK_REALM:-e-skylab}
ADMIN_USER=${KEYCLOAK_ERASURE_ADMIN_USERNAME:-}
KCADM_CONFIG=$(mktemp /tmp/erasure-client-kcadm.XXXXXX)
MODE=dry-run

# shellcheck source=erasure-client-contract.sh
source "$CONFIG_DIR/erasure-client-contract.sh"

cleanup() {
  rm -f "$KCADM_CONFIG"
}
trap cleanup EXIT

usage() {
  printf 'usage: %s --admin-user <administrator> [--apply]\n' "${BASH_SOURCE[0]##*/}" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --admin-user)
      [[ $# -ge 2 ]] || usage
      ADMIN_USER=$2
      shift 2
      ;;
    --apply)
      MODE=apply
      shift
      ;;
    --dry-run)
      MODE=dry-run
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [[ -z $ADMIN_USER ]]; then
  if [[ -t 0 ]]; then
    read -r -p "Keycloak administrator username: " ADMIN_USER
  fi
  [[ -n $ADMIN_USER ]] || usage
fi

log() {
  printf '[erasure-client] %s\n' "$1"
}

changes=0
problems=0

# change "what": counts one change and prints it; a dry run prints "would what".
change() {
  changes=$((changes + 1))
  if [[ $MODE == apply ]]; then
    log "$1"
  else
    log "would $1"
  fi
}

problem() {
  printf '[erasure-client] PROBLEM: %s\n' "$1" >&2
  problems=$((problems + 1))
}

kcadm() {
  local command=$1
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

kcadm_write() {
  local stderr_file status
  stderr_file=$(mktemp /tmp/erasure-client-stderr.XXXXXX)
  if kcadm "$@" >/dev/null 2>"$stderr_file"; then
    status=0
  else
    status=$?
    cat "$stderr_file" >&2
  fi
  rm -f "$stderr_file"
  return "$status"
}

# Runs a lookup that returns 1 for "absent": prints its result (empty when absent) and fails
# only on a real error.
optional_lookup() {
  local result status
  if result=$("$@"); then
    printf '%s\n' "$result"
    return 0
  else
    status=$?
  fi
  if [[ $status == 1 ]]; then
    return 0
  fi
  return "$status"
}

# Prints the id of a client role; 1 when it does not exist.
role_id_of() {
  local client_uuid=$1 wanted=$2 roles_csv id name
  roles_csv=$(kcadm get "clients/$client_uuid/roles" -r "$TARGET_REALM" \
    --fields id,name \
    --format csv \
    --noquotes)
  while IFS=, read -r id name; do
    if [[ $name == "$wanted" ]]; then
      printf '%s\n' "$id"
      return 0
    fi
  done <<<"$roles_csv"
  return 1
}

# id,name CSV lines of a GET that lists roles or scopes (empty lines dropped).
id_name_csv() {
  kcadm get "$1" -r "$TARGET_REALM" --fields id,name --format csv --noquotes | sed '/^$/d'
}

role_body() {
  printf '[{"id":"%s","name":"%s"}]' "$1" "$2"
}

json_list() {
  local out='' item
  for item in "$@"; do
    out+="${out:+,}\"$item\""
  done
  printf '[%s]' "$out"
}

in_list() {
  local wanted=$1 item
  shift
  for item in "$@"; do
    [[ $item == "$wanted" ]] && return 0
  done
  return 1
}

credential_arguments=(
  --config "$KCADM_CONFIG"
  --server "$ADMIN_URL"
  --realm "$ADMIN_REALM"
  --user "$ADMIN_USER"
)
if [[ -n ${KEYCLOAK_ERASURE_ADMIN_PASSWORD:-} ]]; then
  if [[ ${SKY_HARNESS:-} != 1 ]]; then
    printf 'KEYCLOAK_ERASURE_ADMIN_PASSWORD is accepted only by the test harness (SKY_HARNESS=1); unset it and type the password into the kcadm prompt\n' >&2
    exit 2
  fi
  credential_arguments+=(--password "$KEYCLOAK_ERASURE_ADMIN_PASSWORD")
fi
# No redirection: kcadm asks for the password only when stdout is a terminal ("Console is not
# active" otherwise). Its "Logging into" line goes to stderr, so stdout stays clean either way.
"$KCADM" config credentials "${credential_arguments[@]}"
log "realm=$TARGET_REALM client=$ERASURE_CLIENT_ID mode=$MODE"

# --- 1. prerequisites: nothing is written unless all of them exist ---------------------------
resource_uuids=()
missing=''
for i in "${!ERASURE_SERVICES[@]}"; do
  resource_uuids[i]=$(optional_lookup erasure_client_uuid "${ERASURE_RESOURCE_CLIENTS[$i]}")
  [[ -n ${resource_uuids[$i]} ]] || missing="$missing ${ERASURE_RESOURCE_CLIENTS[$i]}"
done
if [[ -n $missing ]]; then
  printf '[erasure-client] resource client(s)%s do not exist in realm %s; nothing was changed. The services own these clients: create them (or fix the realm), then rerun this script\n' \
    "$missing" "$TARGET_REALM" >&2
  exit 1
fi
declare -A default_scope_uuids=()
missing=''
for scope in "${ERASURE_DEFAULT_SCOPES[@]}"; do
  default_scope_uuids[$scope]=$(optional_lookup erasure_scope_uuid "$scope")
  [[ -n ${default_scope_uuids[$scope]} ]] || missing="$missing $scope"
done
if [[ -n $missing ]]; then
  printf '[erasure-client] client scope(s)%s do not exist in realm %s; nothing was changed\n' \
    "$missing" "$TARGET_REALM" >&2
  exit 1
fi

# --- 2. the erase roles on the resource clients -----------------------------------------------
role_ids=()
for i in "${!ERASURE_SERVICES[@]}"; do
  role=${ERASURE_ROLES[$i]}
  resource=${ERASURE_RESOURCE_CLIENTS[$i]}
  if role_ids[i]=$(role_id_of "${resource_uuids[$i]}" "$role"); then
    continue
  fi
  role_ids[i]=''
  change "create client role $role on $resource"
  if [[ $MODE == apply ]]; then
    kcadm_write create "clients/${resource_uuids[$i]}/roles" -r "$TARGET_REALM" \
      -s "name=$role" -s "description=$ERASURE_ROLE_DESCRIPTION"
    role_ids[i]=$(role_id_of "${resource_uuids[$i]}" "$role")
  fi
done

# --- 3. the optional erase scopes: one audience mapper, one role each --------------------------
scope_uuids=()
for i in "${!ERASURE_SERVICES[@]}"; do
  scope=${ERASURE_SCOPES[$i]}
  resource=${ERASURE_RESOURCE_CLIENTS[$i]}
  scope_uuid=$(optional_lookup erasure_scope_uuid "$scope")
  if [[ -z $scope_uuid ]]; then
    change "create optional client scope $scope"
    if [[ $MODE == apply ]]; then
      scope_uuid=$(kcadm create client-scopes -r "$TARGET_REALM" -i \
        -s "name=$scope" \
        -s "description=$ERASURE_SCOPE_DESCRIPTION" \
        -s protocol=openid-connect \
        -s 'attributes."include.in.token.scope"=true' \
        -s 'attributes."display.on.consent.screen"=false')
    fi
  elif [[ $(erasure_scope_protocol "$scope_uuid") != openid-connect ]]; then
    change "set the protocol of scope $scope to openid-connect"
    if [[ $MODE == apply ]]; then
      kcadm_write update "client-scopes/$scope_uuid" -r "$TARGET_REALM" -s protocol=openid-connect
    fi
  fi
  scope_uuids[i]=$scope_uuid

  # Mappers: exactly the audience mapper; any other mapper, or a drifted copy of it, goes.
  expected=$(erasure_expected_mapper "$i")
  mapper_found=false
  if [[ -n $scope_uuid ]]; then
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      mapper_id=${line%%,*}
      mapper_line=${line#*,}
      if [[ $mapper_line == "$expected" && $mapper_found == false ]]; then
        mapper_found=true
        continue
      fi
      change "remove protocol mapper ${mapper_line%%,*} from scope $scope"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "client-scopes/$scope_uuid/protocol-mappers/models/$mapper_id" -r "$TARGET_REALM"
      fi
    done < <(kcadm get "client-scopes/$scope_uuid/protocol-mappers/models" -r "$TARGET_REALM" \
      --fields "id,$ERASURE_MAPPER_FIELDS" --format csv --noquotes)
  fi
  if [[ $mapper_found == false ]]; then
    change "add audience mapper $scope-audience (aud $resource) to scope $scope"
    if [[ $MODE == apply ]]; then
      kcadm_write create "client-scopes/$scope_uuid/protocol-mappers/models" -r "$TARGET_REALM" -b \
        "{\"name\":\"$scope-audience\",\"protocol\":\"openid-connect\",\"protocolMapper\":\"oidc-audience-mapper\",\"consentRequired\":false,\"config\":{\"included.client.audience\":\"$resource\",\"id.token.claim\":\"false\",\"access.token.claim\":\"true\",\"introspection.token.claim\":\"true\",\"userinfo.token.claim\":\"false\"}}"
    fi
  fi

  # Role scope mappings: no realm role, only this service's erase role among the resource clients.
  if [[ -n $scope_uuid ]]; then
    while IFS=, read -r role_id role_name; do
      change "remove realm role $role_name from scope $scope"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "client-scopes/$scope_uuid/scope-mappings/realm" -r "$TARGET_REALM" \
          -b "$(role_body "$role_id" "$role_name")"
      fi
    done < <(id_name_csv "client-scopes/$scope_uuid/scope-mappings/realm")
  fi
  for j in "${!ERASURE_SERVICES[@]}"; do
    mapped=''
    if [[ -n $scope_uuid ]]; then
      mapped=$(id_name_csv "client-scopes/$scope_uuid/scope-mappings/clients/${resource_uuids[$j]}")
    fi
    while IFS=, read -r role_id role_name; do
      [[ -n $role_id ]] || continue
      [[ $j == "$i" && $role_name == "${ERASURE_ROLES[$i]}" ]] && continue
      change "remove role ${ERASURE_RESOURCE_CLIENTS[$j]}/$role_name from scope $scope"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "client-scopes/$scope_uuid/scope-mappings/clients/${resource_uuids[$j]}" \
          -r "$TARGET_REALM" -b "$(role_body "$role_id" "$role_name")"
      fi
    done <<<"$mapped"
    if [[ $j == "$i" ]] && ! grep -Eq "^[^,]+,${ERASURE_ROLES[$i]}\$" <<<"$mapped"; then
      change "map role $resource/${ERASURE_ROLES[$i]} in scope $scope"
      if [[ $MODE == apply ]]; then
        kcadm_write create "client-scopes/$scope_uuid/scope-mappings/clients/${resource_uuids[$i]}" \
          -r "$TARGET_REALM" -b "$(role_body "${role_ids[$i]}" "${ERASURE_ROLES[$i]}")"
      fi
    fi
  done
done

# --- 4. the client ------------------------------------------------------------------------------
client_uuid=$(optional_lookup erasure_client_uuid "$ERASURE_CLIENT_ID")
if [[ -n $client_uuid ]]; then
  live_flags=$(erasure_client_flags "$client_uuid")
  if [[ $live_flags == "$ERASURE_FLAG_VALUES" ]]; then
    log "client $ERASURE_CLIENT_ID: flags unchanged"
  else
    change "update client $ERASURE_CLIENT_ID flags ($ERASURE_FLAG_FIELDS: $live_flags -> $ERASURE_FLAG_VALUES)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" \
        -s "name=$ERASURE_CLIENT_NAME" \
        -s "description=$ERASURE_CLIENT_DESCRIPTION" \
        "${ERASURE_FLAG_SETTINGS[@]}"
    fi
  fi
else
  change "create confidential service-account client $ERASURE_CLIENT_ID (secret generated by Keycloak; default scopes ${ERASURE_DEFAULT_SCOPES[*]}; optional scopes ${ERASURE_SCOPES[*]})"
  if [[ $MODE == apply ]]; then
    client_uuid=$(kcadm create clients -r "$TARGET_REALM" -i \
      -s "clientId=$ERASURE_CLIENT_ID" \
      -s "name=$ERASURE_CLIENT_NAME" \
      -s "description=$ERASURE_CLIENT_DESCRIPTION" \
      -s protocol=openid-connect \
      "${ERASURE_FLAG_SETTINGS[@]}" \
      -s "defaultClientScopes=$(json_list "${ERASURE_DEFAULT_SCOPES[@]}")" \
      -s "optionalClientScopes=$(json_list "${ERASURE_SCOPES[@]}")")
    log "client $ERASURE_CLIENT_ID: created (the secret is never printed; ops/wizards/core-erasure-client-wizard.sh moves it into OpenBao)"
  fi
fi

# --- 5. default and optional scopes: exactly the contract --------------------------------------
if [[ -n $client_uuid ]]; then
  live_default=$(id_name_csv "clients/$client_uuid/default-client-scopes")
  live_optional=$(id_name_csv "clients/$client_uuid/optional-client-scopes")
else
  # Dry run of a missing client: the creation attaches exactly the contract's scopes.
  live_default=''
  for scope in "${ERASURE_DEFAULT_SCOPES[@]}"; do
    live_default+="${default_scope_uuids[$scope]},$scope"$'\n'
  done
  live_optional=''
  for i in "${!ERASURE_SERVICES[@]}"; do
    live_optional+="-,${ERASURE_SCOPES[$i]}"$'\n'
  done
fi
# Detach first: a scope moves between the two lists only after it has left the other one.
while IFS=, read -r scope_id scope_name; do
  [[ -n $scope_id ]] || continue
  in_list "$scope_name" "${ERASURE_DEFAULT_SCOPES[@]}" "$ERASURE_TOLERATED_DEFAULT_SCOPE" && continue
  change "detach default scope $scope_name from $ERASURE_CLIENT_ID"
  if [[ $MODE == apply ]]; then
    kcadm_write delete "clients/$client_uuid/default-client-scopes/$scope_id" -r "$TARGET_REALM"
  fi
done <<<"$live_default"
while IFS=, read -r scope_id scope_name; do
  [[ -n $scope_id ]] || continue
  in_list "$scope_name" "${ERASURE_SCOPES[@]}" && continue
  change "detach optional scope $scope_name from $ERASURE_CLIENT_ID"
  if [[ $MODE == apply ]]; then
    kcadm_write delete "clients/$client_uuid/optional-client-scopes/$scope_id" -r "$TARGET_REALM"
  fi
done <<<"$live_optional"
for scope in "${ERASURE_DEFAULT_SCOPES[@]}"; do
  grep -Eq "^[^,]+,$scope\$" <<<"$live_default" && continue
  change "attach default scope $scope to $ERASURE_CLIENT_ID"
  if [[ $MODE == apply ]]; then
    kcadm_write update "clients/$client_uuid/default-client-scopes/${default_scope_uuids[$scope]}" \
      -r "$TARGET_REALM" -n -b '{}'
  fi
done
for i in "${!ERASURE_SERVICES[@]}"; do
  grep -Eq "^[^,]+,${ERASURE_SCOPES[$i]}\$" <<<"$live_optional" && continue
  change "attach optional scope ${ERASURE_SCOPES[$i]} to $ERASURE_CLIENT_ID"
  if [[ $MODE == apply ]]; then
    kcadm_write update "clients/$client_uuid/optional-client-scopes/${scope_uuids[$i]}" \
      -r "$TARGET_REALM" -n -b '{}'
  fi
done

# --- 6. no direct scope mappings: a role reaches a token only through an erase scope ----------
if [[ -n $client_uuid ]]; then
  while IFS=, read -r role_id role_name; do
    change "remove direct realm scope mapping $role_name from $ERASURE_CLIENT_ID"
    if [[ $MODE == apply ]]; then
      kcadm_write delete "clients/$client_uuid/scope-mappings/realm" -r "$TARGET_REALM" \
        -b "$(role_body "$role_id" "$role_name")"
    fi
  done < <(id_name_csv "clients/$client_uuid/scope-mappings/realm")
  for j in "${!ERASURE_SERVICES[@]}"; do
    while IFS=, read -r role_id role_name; do
      change "remove direct scope mapping ${ERASURE_RESOURCE_CLIENTS[$j]}/$role_name from $ERASURE_CLIENT_ID"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "clients/$client_uuid/scope-mappings/clients/${resource_uuids[$j]}" \
          -r "$TARGET_REALM" -b "$(role_body "$role_id" "$role_name")"
      fi
    done < <(id_name_csv "clients/$client_uuid/scope-mappings/clients/${resource_uuids[$j]}")
  done
fi

# --- 7. the service account holds exactly the three erase roles of these clients ---------------
service_user_id=''
if [[ -n $client_uuid ]]; then
  service_user_id=$(kcadm get "clients/$client_uuid/service-account-user" -r "$TARGET_REALM" \
    --fields id \
    --format csv \
    --noquotes)
  [[ -n $service_user_id && $service_user_id != *,* ]] || {
    printf 'The %s service-account user could not be resolved exactly\n' "$ERASURE_CLIENT_ID" >&2
    exit 1
  }
fi
for j in "${!ERASURE_SERVICES[@]}"; do
  resource=${ERASURE_RESOURCE_CLIENTS[$j]}
  assigned=''
  if [[ -n $service_user_id ]]; then
    assigned=$(id_name_csv "users/$service_user_id/role-mappings/clients/${resource_uuids[$j]}")
  fi
  while IFS=, read -r role_id role_name; do
    [[ -n $role_id && $role_name != "${ERASURE_ROLES[$j]}" ]] || continue
    change "remove role $resource/$role_name from $ERASURE_SERVICE_ACCOUNT"
    if [[ $MODE == apply ]]; then
      kcadm_write delete "users/$service_user_id/role-mappings/clients/${resource_uuids[$j]}" \
        -r "$TARGET_REALM" -b "$(role_body "$role_id" "$role_name")"
    fi
  done <<<"$assigned"
  if ! grep -Eq "^[^,]+,${ERASURE_ROLES[$j]}\$" <<<"$assigned"; then
    change "assign role $resource/${ERASURE_ROLES[$j]} to $ERASURE_SERVICE_ACCOUNT"
    if [[ $MODE == apply ]]; then
      kcadm_write create "users/$service_user_id/role-mappings/clients/${resource_uuids[$j]}" \
        -r "$TARGET_REALM" -b "$(role_body "${role_ids[$j]}" "${ERASURE_ROLES[$j]}")"
    fi
  fi
done

# --- 8. nobody else holds an erase role (reported, never removed) --------------------------------
for j in "${!ERASURE_SERVICES[@]}"; do
  [[ -n ${role_ids[$j]} ]] || continue
  role_path="clients/${resource_uuids[$j]}/roles/${ERASURE_ROLES[$j]}"
  others=$(kcadm get "$role_path/users" -r "$TARGET_REALM" --fields username --format csv --noquotes \
    | sed '/^$/d' | { grep -Fvx "$ERASURE_SERVICE_ACCOUNT" || true; } | wc -l | tr -d ' ')
  groups=$(kcadm get "$role_path/groups" -r "$TARGET_REALM" --fields id --format csv --noquotes \
    | sed '/^$/d' | wc -l | tr -d ' ')
  if [[ $others != 0 || $groups != 0 ]]; then
    problem "${ERASURE_RESOURCE_CLIENTS[$j]}/${ERASURE_ROLES[$j]} is also held by $others other user(s) and $groups group(s); only $ERASURE_SERVICE_ACCOUNT may hold it. Remove those grants by hand (Admin Console → Clients → ${ERASURE_RESOURCE_CLIENTS[$j]} → Roles → ${ERASURE_ROLES[$j]} → Users in role)"
  fi
done

if [[ $MODE == apply ]]; then
  log "applied $changes change(s); the reconciler now verifies $ERASURE_CLIENT_ID on every run"
else
  log "dry run: $changes change(s) pending; rerun with --apply to execute them"
fi
if [[ $problems != 0 ]]; then
  log "$problems problem(s) need a manual decision (see above)"
  exit 1
fi
