#!/usr/bin/env bash
# Idempotent provisioning of the Site login clients of the SANDBOX realm (e-skylab-sandbox). The
# sandbox realm had no site client, so sandbox-arge.yildizskylab.com ran without a login and its
# CMS editor could not be tried. Today it makes one client, frontend-arge, shaped like the one in
# production (e-skylab, made by hand there):
#   - confidential (client secret generated by Keycloak, never printed), standard flow on
#     (NextAuth's Keycloak provider, callback /api/auth/callback/keycloak), implicit and direct
#     grants off, service account on (the site reads content and pushes collection schemas with
#     client_credentials), fullScopeAllowed=true;
#   - redirect URI https://sandbox-arge.yildizskylab.com/*, web origin
#     https://sandbox-arge.yildizskylab.com, post-logout redirect https://sandbox-arge.yildizskylab.com/*;
#     other URIs already on the client are kept and listed (a developer may add localhost);
#   - skycms in the access token's aud (inscribed checks it): an audience mapper already reaching
#     the access token (client mapper or default scope) is enough, otherwise the client mapper
#     skycms-audience is added (access token and introspection, not the ID token);
#   - core in aud when the realm has a core client (arge's CMS uploads go to core /v1/media with the
#     editor's token): the scope frontend-arge-core-audience exactly as the reconciler makes it in
#     production (reconcile_login_client_audience, config/frontend-arge-core-audience-mappers.json),
#     as a default scope of the client. Without a core client it is skipped with a NOTE;
#   - groups as full paths in the access token (inscribed's collections read them): an existing
#     full-path Group Membership mapper on the client or a default scope is enough; otherwise the
#     realm scope "groups" is attached as a default scope when it only carries such mappers (the
#     production shape), else the client mapper groups is added. A groups claim written differently
#     (flat names) is a PROBLEM and is never changed.
# frontend-main is NOT made: there is no sandbox main-site app today. Add it here when one exists.
#
# The CMS roles (content:read, content:write, schema:sync, cms:access, client:admin), the flat roles
# claim and the service account's grants are NOT made here: config/inscribed-cms-roles.sh makes
# them, run after this script with KEYCLOAK_REALM=e-skylab-sandbox --client frontend-arge. Nothing
# is ever granted to a group or a person, nothing is removed.
#
# It refuses every realm but e-skylab-sandbox (production, e-skylab, is never written), before it
# logs in. It needs the realm and its skycms client; without them it stops and writes nothing.
#
# Usage (inside the Keycloak image, as an operator):
#   sandbox-site-clients.sh --admin-user <admin>             # --check (default): state and plan
#   sandbox-site-clients.sh --admin-user <admin> --apply     # creates and repairs
#   sandbox-site-clients.sh --kcadm-config <file> [--apply]  # reuse a logged-in kcadm session
#
# The administrator password is typed into kcadm's own prompt and never passes through this
# script. --kcadm-config reuses a kcadm config file an operator (or the wizard) already logged in
# with; the script then never logs in and never deletes that file. Environment: KEYCLOAK_ADMIN_URL
# (default http://keycloak:8080), KEYCLOAK_REALM (default e-skylab-sandbox, the only one accepted),
# KEYCLOAK_ADMIN_REALM (default master), KEYCLOAK_SANDBOX_CLIENTS_ADMIN_USERNAME (or --admin-user).
#
# Output: one "[sandbox-clients] ..." line per fact, change ("would ..." in --check), NOTE, WARNING
# and PROBLEM, then "check: N change(s) pending, W warning(s), P problem(s)" or "applied N
# change(s), ...". Exit 0 unless a PROBLEM or a missing prerequisite (1) or a usage error or a
# refused realm (2). No secret is ever read or printed.
# Operators: ops/wizards/sandbox-arge-keycloak-wizard.sh in sky_lab_genel runs it; afterwards
# ops/wizards/arge-dokploy-wizard.sh --sandbox-kc moves the client secret into OpenBao.
set -Eeuo pipefail
shopt -s inherit_errexit

umask 077

KCADM=${KCADM_BIN:-/opt/keycloak/bin/kcadm.sh}
ADMIN_URL=${KEYCLOAK_ADMIN_URL:-http://keycloak:8080}
ADMIN_REALM=${KEYCLOAK_ADMIN_REALM:-master}
SANDBOX_REALM=e-skylab-sandbox
TARGET_REALM=${KEYCLOAK_REALM:-$SANDBOX_REALM}
ADMIN_USER=${KEYCLOAK_SANDBOX_CLIENTS_ADMIN_USERNAME:-}
KCADM_CONFIG=''
OWN_CONFIG=false
MODE=check

CLIENT_ID=frontend-arge
CLIENT_NAME='arge (sandbox)'
CLIENT_DESCRIPTION='sandbox-arge.yildizskylab.com: NextAuth login and server-side CMS reads. Made by config/sandbox-site-clients.sh'
SITE_ORIGIN=https://sandbox-arge.yildizskylab.com
REDIRECT_URI="$SITE_ORIGIN/*"
POST_LOGOUT_URI="$SITE_ORIGIN/*"
# The production client's flags. fullScopeAllowed=true as relayed from production (2026-09-28);
# e-skylab-keycloak#47 and the harness of inscribed-cms-roles.sh describe it as false. The site
# works either way: its CMS roles are its own client roles, which a token always carries.
FLAG_FIELDS='enabled,protocol,publicClient,bearerOnly,clientAuthenticatorType,standardFlowEnabled,implicitFlowEnabled,directAccessGrantsEnabled,serviceAccountsEnabled,fullScopeAllowed,consentRequired'
FLAG_VALUES='true,openid-connect,false,false,client-secret,true,false,false,true,true,false'
FLAG_SETTINGS=(
  -s enabled=true
  -s protocol=openid-connect
  -s publicClient=false
  -s bearerOnly=false
  -s clientAuthenticatorType=client-secret
  -s standardFlowEnabled=true
  -s implicitFlowEnabled=false
  -s directAccessGrantsEnabled=false
  -s serviceAccountsEnabled=true
  -s fullScopeAllowed=true
  -s consentRequired=false
)
RESOURCE_CLIENT=skycms
CORE_CLIENT=core
SKYCMS_MAPPER=skycms-audience
CORE_SCOPE=frontend-arge-core-audience
CORE_MAPPER=core-audience
GROUPS_CLAIM=groups
GROUPS_SCOPE=groups
GROUPS_MAPPER=groups
# Mapper CSV: the free-text name last, so a comma in it cannot shift the other columns.
MAPPER_FIELDS='id,protocolMapper,config(claim.name,full.path,included.client.audience,access.token.claim,id.token.claim,introspection.token.claim),name'

usage() {
  printf 'usage: %s (--admin-user <administrator> | --kcadm-config <file>) [--check | --apply]\n' \
    "${BASH_SOURCE[0]##*/}" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --admin-user)
      [[ $# -ge 2 ]] || usage
      ADMIN_USER=$2
      shift 2
      ;;
    --kcadm-config)
      [[ $# -ge 2 ]] || usage
      KCADM_CONFIG=$2
      shift 2
      ;;
    --apply)
      MODE=apply
      shift
      ;;
    --check | --dry-run)
      MODE=check
      shift
      ;;
    *)
      usage
      ;;
  esac
done

# Before anything else, and before a login: only the sandbox realm is ever written.
if [[ $TARGET_REALM != "$SANDBOX_REALM" ]]; then
  printf '[sandbox-clients] refusing realm %s: this script writes only the sandbox realm %s (production, e-skylab, is never touched); nothing was read or changed\n' \
    "$TARGET_REALM" "$SANDBOX_REALM" >&2
  exit 2
fi

if [[ -z $KCADM_CONFIG ]]; then
  if [[ -z $ADMIN_USER ]]; then
    if [[ -t 0 ]]; then
      read -r -p "Keycloak administrator username: " ADMIN_USER
    fi
    [[ -n $ADMIN_USER ]] || usage
  fi
  KCADM_CONFIG=$(mktemp /tmp/sandbox-clients-kcadm.XXXXXX)
  OWN_CONFIG=true
elif [[ ! -r $KCADM_CONFIG ]]; then
  printf 'kcadm config %s is not readable\n' "$KCADM_CONFIG" >&2
  exit 2
fi

cleanup() {
  if [[ $OWN_CONFIG == true ]]; then
    rm -f "$KCADM_CONFIG"
  fi
}
trap cleanup EXIT

log() {
  printf '[sandbox-clients] %s\n' "$1"
}

changes=0
warnings=0
problems=0

# change "what": counts one change and prints it; --check prints "would what".
change() {
  changes=$((changes + 1))
  if [[ $MODE == apply ]]; then
    log "$1"
  else
    log "would $1"
  fi
}

warning() {
  warnings=$((warnings + 1))
  log "WARNING: $1"
}

problem() {
  problems=$((problems + 1))
  log "PROBLEM: $1"
}

kcadm() {
  local command=$1
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

kcadm_write() {
  local stderr_file status
  stderr_file=$(mktemp /tmp/sandbox-clients-stderr.XXXXXX)
  if kcadm "$@" >/dev/null 2>"$stderr_file"; then
    status=0
  else
    status=$?
    cat "$stderr_file" >&2
  fi
  rm -f "$stderr_file"
  return "$status"
}

# csv PATH FIELDS [kcadm arguments]: the CSV lines of a GET in the target realm (no quotes,
# empty lines dropped).
csv() {
  kcadm get "$1" -r "$TARGET_REALM" --fields "$2" --format csv --noquotes "${@:3}" | tr -d '\r' | sed '/^$/d'
}

# in_list WORD ITEM...: whether WORD is one of the items.
in_list() {
  local wanted=$1 item
  shift
  for item in "$@"; do
    [[ $item == "$wanted" ]] && return 0
  done
  return 1
}

# json_strings ITEM...: a JSON array of plain strings (URIs; a quote or backslash is refused).
json_strings() {
  local out='' item
  for item in "$@"; do
    [[ $item != *[\"\\]* ]] || { printf 'refusing to write the value %s\n' "$item" >&2; exit 1; }
    out+="${out:+,}\"$item\""
  done
  printf '[%s]' "$out"
}

# uuid_by CLIENT_ID: the id of the client with exactly this clientId (empty when absent).
uuid_by() {
  csv clients id,clientId -q "clientId=$1" | while IFS=, read -r id client_id; do
    if [[ $client_id == "$1" ]]; then printf '%s\n' "$id"; fi
  done
}

# scope_ids NAME: the ids of the client scopes with exactly this name, one per line.
scope_ids() {
  csv client-scopes id,name | while IFS=, read -r id name; do
    if [[ $name == "$1" ]]; then printf '%s\n' "$id"; fi
  done
}

# listed CLIENT_UUID PATH ID: whether ID is among the ids a client's scope list returns (grep reads
# the whole list: an early exit would make kcadm's pipe fail under pipefail).
listed() {
  csv "clients/$1/$2" id | grep -Fx "$3" >/dev/null
}

# ensure_listed FIELD WANTED LABEL [ALSO_ENOUGH...]: WANTED must be in the client's list FIELD (or
# one of ALSO_ENOUGH, e.g. "+" for web origins); other entries are kept and listed.
ensure_listed() {
  local field=$1 wanted=$2 label=$3 items=() item extras='' present=false
  shift 3
  while IFS= read -r item; do
    if [[ -n $item ]]; then items+=("$item"); fi
  done < <(csv "clients/$client_uuid" "$field" | tr ',' '\n')
  for item in "${items[@]}"; do
    if [[ $item == "$wanted" ]] || in_list "$item" "$@"; then
      present=true
    else
      extras+="${extras:+ }$item"
    fi
  done
  [[ -z $extras ]] || log "NOTE: $CLIENT_ID also has $label(s) $extras (left as is)"
  if [[ $present == true ]]; then
    log "$CLIENT_ID: $label $wanted allowed"
    return 0
  fi
  change "add $label $wanted to $CLIENT_ID"
  if [[ $MODE == apply ]]; then
    items+=("$wanted")
    kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" -s "$field=$(json_strings "${items[@]}")"
  fi
}

audience_mapper_body() { # audience_mapper_body NAME AUDIENCE [ID]
  local id_field=''
  [[ -z ${3:-} ]] || id_field="\"id\":\"$3\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-audience-mapper","consentRequired":false,"config":{"included.client.audience":"%s","id.token.claim":"false","access.token.claim":"true","introspection.token.claim":"true"}}' \
    "$id_field" "$1" "$2"
}

groups_mapper_body() { # groups_mapper_body [ID]
  local id_field=''
  [[ -z ${1:-} ]] || id_field="\"id\":\"$1\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-group-membership-mapper","consentRequired":false,"config":{"claim.name":"%s","full.path":"true","multivalued":"true","access.token.claim":"true","id.token.claim":"false","userinfo.token.claim":"false","introspection.token.claim":"true","lightweight.claim":"false"}}' \
    "$id_field" "$GROUPS_MAPPER" "$GROUPS_CLAIM"
}

# The production shape of frontend-arge-core-audience (reconcile-account-center.sh's
# ensure_client_scope and config/frontend-arge-core-audience-mappers.json; the harness compares).
CORE_SCOPE_BODY="{\"name\":\"$CORE_SCOPE\",\"protocol\":\"openid-connect\",\"attributes\":{\"include.in.token.scope\":\"false\",\"display.on.consent.screen\":\"false\"}}"

# Mapper CSV columns after id: type, claim, full path, audience, access, id token, introspection.
# is_audience_to LINE AUDIENCE: the mapper puts AUDIENCE into the access token's aud.
is_audience_to() {
  local type claim full audience access rest
  IFS=, read -r type claim full audience access rest <<<"$1"
  [[ $type == oidc-audience-mapper && $audience == "$2" && $access == true ]]
}
# own_audience_ok LINE AUDIENCE: exactly the shape audience_mapper_body writes.
own_audience_ok() {
  local type claim full audience access id_token introspection
  IFS=, read -r type claim full audience access id_token introspection <<<"$1"
  [[ $type == oidc-audience-mapper && $audience == "$2" && $access == true && $id_token == false && $introspection == true ]]
}
# groups_kind LINE: none (does not write groups into the access token), good (full path) or bad.
groups_kind() {
  local type claim full audience access rest
  IFS=, read -r type claim full audience access rest <<<"$1"
  if [[ $claim != "$GROUPS_CLAIM" && $claim != "$GROUPS_CLAIM".* ]] || [[ $access != true ]]; then
    printf 'none'
  elif [[ $type == oidc-group-membership-mapper && $claim == "$GROUPS_CLAIM" && $full == true ]]; then
    printf 'good'
  else
    printf 'bad'
  fi
}
own_groups_ok() {
  local type claim full audience access id_token introspection
  IFS=, read -r type claim full audience access id_token introspection <<<"$1"
  [[ $type == oidc-group-membership-mapper && $claim == "$GROUPS_CLAIM" && $full == true && $access == true && $introspection == true ]]
}

credential_arguments=(
  --config "$KCADM_CONFIG"
  --server "$ADMIN_URL"
  --realm "$ADMIN_REALM"
  --user "$ADMIN_USER"
)
if [[ $OWN_CONFIG == true ]]; then
  # No redirection: kcadm asks for the password only when stdout is a terminal ("Console is not
  # active" otherwise). Its "Logging into" line goes to stderr, so stdout stays clean either way.
  "$KCADM" config credentials "${credential_arguments[@]}"
fi
log "realm=$TARGET_REALM mode=$MODE clients=$CLIENT_ID"

# --- prerequisites: nothing is written unless they hold ------------------------------------------
if ! realm_name=$(kcadm get "realms/$TARGET_REALM" --fields realm --format csv --noquotes 2>/dev/null | tr -d '\r') \
  || [[ $realm_name != "$TARGET_REALM" ]]; then
  printf '[sandbox-clients] realm %s does not exist or cannot be read; nothing was changed\n' "$TARGET_REALM" >&2
  exit 1
fi
if [[ -z $(uuid_by "$RESOURCE_CLIENT") ]]; then
  printf '[sandbox-clients] the %s client (inscribed'"'"'s audience) does not exist in realm %s; nothing was changed. Create it first (inscribed-sandbox-setup-wizard.sh expects it), then rerun\n' \
    "$RESOURCE_CLIENT" "$TARGET_REALM" >&2
  exit 1
fi
core_uuid=$(uuid_by "$CORE_CLIENT")
log "NOTE: frontend-main is not made: there is no sandbox main-site app; add it here when one exists"

# --- 1. the client ------------------------------------------------------------------------------
client_uuid=$(uuid_by "$CLIENT_ID")
created=false
if [[ -z $client_uuid ]]; then
  change "create confidential client $CLIENT_ID (standard flow and service account on, implicit and direct grants off, fullScopeAllowed=true; redirect $REDIRECT_URI, web origin $SITE_ORIGIN, post-logout $POST_LOGOUT_URI; the secret is generated by Keycloak and never printed)"
  if [[ $MODE == apply ]]; then
    client_uuid=$(kcadm create clients -r "$TARGET_REALM" -i \
      -s "clientId=$CLIENT_ID" \
      -s "name=$CLIENT_NAME" \
      -s "description=$CLIENT_DESCRIPTION" \
      "${FLAG_SETTINGS[@]}" \
      -s "redirectUris=$(json_strings "$REDIRECT_URI")" \
      -s "webOrigins=$(json_strings "$SITE_ORIGIN")" \
      -s "attributes.\"post.logout.redirect.uris\"=$POST_LOGOUT_URI" | tr -d '\r')
    [[ -n $client_uuid ]] || { printf 'client %s was not created\n' "$CLIENT_ID" >&2; exit 1; }
    created=true
  fi
else
  live_flags=$(csv "clients/$client_uuid" "$FLAG_FIELDS")
  if [[ $live_flags == "$FLAG_VALUES" ]]; then
    log "$CLIENT_ID: flags unchanged ($FLAG_FIELDS=$live_flags)"
  else
    change "update $CLIENT_ID flags ($FLAG_FIELDS: $live_flags -> $FLAG_VALUES)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" "${FLAG_SETTINGS[@]}"
    fi
  fi

  # URIs: the site's must be there; others are kept and listed.
  ensure_listed redirectUris "$REDIRECT_URI" 'redirect URI'
  # "+" allows the origins of the redirect URIs, the site's among them.
  ensure_listed webOrigins "$SITE_ORIGIN" 'web origin' '+'

  post_logout=$(csv "clients/$client_uuid" 'attributes(post.logout.redirect.uris)')
  post_items=()
  while IFS= read -r item; do
    if [[ -n $item ]]; then post_items+=("$item"); fi
  done <<<"${post_logout//##/$'\n'}"
  if [[ ${#post_items[@]} -gt 0 ]] && { in_list "$POST_LOGOUT_URI" "${post_items[@]}" || in_list '+' "${post_items[@]}"; }; then
    log "$CLIENT_ID: post-logout redirect $POST_LOGOUT_URI allowed"
  else
    change "add post-logout redirect $POST_LOGOUT_URI to $CLIENT_ID"
    if [[ $MODE == apply ]]; then
      post_items+=("$POST_LOGOUT_URI")
      joined=$(printf '%s##' "${post_items[@]}")
      kcadm_write update "clients/$client_uuid" -r "$TARGET_REALM" \
        -s "attributes.\"post.logout.redirect.uris\"=${joined%##}"
    fi
  fi
fi
[[ $created == false ]] || log "$CLIENT_ID: created (id $client_uuid; the secret is never printed: ops/wizards/arge-dokploy-wizard.sh --sandbox-kc moves it into OpenBao)"

# --- 2. what reaches the access token: the client's mappers and its default scopes ---------------
# A client still to be made (--check) would get the realm's default OpenID Connect scopes.
client_mappers=''
declare -A default_scope_by_name=()
if [[ -n $client_uuid ]]; then
  client_mappers=$(csv "clients/$client_uuid/protocol-mappers/models" "$MAPPER_FIELDS")
  while IFS=, read -r scope_id scope_name; do
    if [[ -n $scope_id ]]; then default_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv "clients/$client_uuid/default-client-scopes" id,name)
else
  while IFS=, read -r scope_id scope_name scope_protocol; do
    if [[ -n $scope_id && $scope_protocol == openid-connect ]]; then default_scope_by_name[$scope_name]=$scope_id; fi
  done < <(csv default-default-client-scopes id,name,protocol)
fi

own_skycms_line=''
own_groups_line=''
skycms_sources=()
good_groups=()
bad_groups=()
# consider WHERE LINE (id,type,...,name): sorts one mapper that reaches the access token.
consider() {
  local where=$1 line=$2 rest=${2#*,}
  rest=${rest%,*}
  if is_audience_to "$rest" "$RESOURCE_CLIENT"; then
    skycms_sources+=("$where")
  fi
  case $(groups_kind "$rest") in
    good) good_groups+=("$where") ;;
    bad) bad_groups+=("$where") ;;
  esac
}
while IFS= read -r line; do
  [[ -n $line ]] || continue
  name=${line##*,}
  type=${line#*,}
  type=${type%%,*}
  if [[ $name == "$SKYCMS_MAPPER" || $name == "$GROUPS_MAPPER" ]]; then
    if [[ $name == "$SKYCMS_MAPPER" && $type == oidc-audience-mapper ]]; then
      own_skycms_line=$line
      continue
    elif [[ $name == "$GROUPS_MAPPER" && $type == oidc-group-membership-mapper ]]; then
      own_groups_line=$line
      continue
    fi
    problem "$CLIENT_ID has a mapper named $name of type $type; rename or remove it by hand"
  fi
  consider "client mapper $name" "$line"
done <<<"$client_mappers"
while IFS= read -r scope_name; do
  [[ -n $scope_name ]] || continue
  while IFS= read -r line; do
    [[ -n $line ]] || continue
    consider "default scope $scope_name mapper ${line##*,}" "$line"
  done < <(csv "client-scopes/${default_scope_by_name[$scope_name]}/protocol-mappers/models" "$MAPPER_FIELDS")
done < <(printf '%s\n' "${!default_scope_by_name[@]}" | sort)

# --- 3. aud skycms ------------------------------------------------------------------------------
if [[ -n $own_skycms_line ]]; then
  own_rest=${own_skycms_line#*,}
  if own_audience_ok "${own_rest%,*}" "$RESOURCE_CLIENT"; then
    log "$CLIENT_ID: mapper $SKYCMS_MAPPER unchanged (aud += $RESOURCE_CLIENT)"
  else
    change "repair mapper $SKYCMS_MAPPER on $CLIENT_ID (${own_rest%,*} -> aud $RESOURCE_CLIENT, access token and introspection, not the ID token)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid/protocol-mappers/models/${own_skycms_line%%,*}" -r "$TARGET_REALM" \
        -b "$(audience_mapper_body "$SKYCMS_MAPPER" "$RESOURCE_CLIENT" "${own_skycms_line%%,*}")"
    fi
  fi
elif [[ ${#skycms_sources[@]} -gt 0 ]]; then
  log "$CLIENT_ID: aud $RESOURCE_CLIENT comes from ${skycms_sources[*]}"
else
  change "add mapper $SKYCMS_MAPPER to $CLIENT_ID (aud += $RESOURCE_CLIENT; access token and introspection, not the ID token)"
  if [[ $MODE == apply ]]; then
    kcadm_write create "clients/$client_uuid/protocol-mappers/models" -r "$TARGET_REALM" \
      -b "$(audience_mapper_body "$SKYCMS_MAPPER" "$RESOURCE_CLIENT")"
  fi
fi

# --- 4. aud core: the reconciler's scope, as a default scope --------------------------------------
if [[ -z $core_uuid ]]; then
  log "NOTE: realm $TARGET_REALM has no $CORE_CLIENT client; $CORE_SCOPE skipped (rerun once core's client exists)"
else
  scope_list=$(scope_ids "$CORE_SCOPE")
  scope_count=$(sed '/^$/d' <<<"$scope_list" | wc -l | tr -d ' ')
  core_scope_uuid=''
  if [[ $scope_count -gt 1 ]]; then
    problem "$scope_count client scopes are named $CORE_SCOPE; keep one by hand (Admin Console -> Client scopes)"
  elif [[ $scope_count == 0 ]]; then
    change "create client scope $CORE_SCOPE (include.in.token.scope=false, display.on.consent.screen=false)"
    if [[ $MODE == apply ]]; then
      core_scope_uuid=$(kcadm create client-scopes -r "$TARGET_REALM" -i -b "$CORE_SCOPE_BODY" | tr -d '\r')
      [[ -n $core_scope_uuid ]] || { printf 'client scope %s was not created\n' "$CORE_SCOPE" >&2; exit 1; }
    fi
  else
    core_scope_uuid=$scope_list
    shape=$(csv "client-scopes/$core_scope_uuid" 'protocol,attributes(include.in.token.scope,display.on.consent.screen)')
    if [[ $shape == 'openid-connect,false,false' ]]; then
      log "client scope $CORE_SCOPE: attributes unchanged"
    else
      change "update client scope $CORE_SCOPE (protocol,include.in.token.scope,display.on.consent.screen: $shape -> openid-connect,false,false)"
      if [[ $MODE == apply ]]; then
        kcadm_write update "client-scopes/$core_scope_uuid" -r "$TARGET_REALM" -s protocol=openid-connect \
          -s 'attributes."include.in.token.scope"=false' -s 'attributes."display.on.consent.screen"=false'
      fi
    fi
  fi
  if [[ $scope_count -le 1 ]]; then
    core_mapper_line=''
    if [[ -n $core_scope_uuid ]]; then
      while IFS= read -r line; do
        [[ -n $line ]] || continue
        if [[ ${line##*,} == "$CORE_MAPPER" && -z $core_mapper_line ]]; then
          core_mapper_line=$line
        else
          problem "client scope $CORE_SCOPE also has the mapper ${line##*,}; production's has only $CORE_MAPPER. Remove it by hand"
        fi
      done < <(csv "client-scopes/$core_scope_uuid/protocol-mappers/models" "$MAPPER_FIELDS")
    fi
    if [[ -z $core_mapper_line ]]; then
      change "add mapper $CORE_MAPPER to $CORE_SCOPE (aud += $CORE_CLIENT; access token and introspection, not the ID token)"
      if [[ $MODE == apply ]]; then
        kcadm_write create "client-scopes/$core_scope_uuid/protocol-mappers/models" -r "$TARGET_REALM" \
          -b "$(audience_mapper_body "$CORE_MAPPER" "$CORE_CLIENT")"
      fi
    else
      core_rest=${core_mapper_line#*,}
      if own_audience_ok "${core_rest%,*}" "$CORE_CLIENT"; then
        log "client scope $CORE_SCOPE: mapper $CORE_MAPPER unchanged"
      else
        change "repair mapper $CORE_MAPPER in $CORE_SCOPE (${core_rest%,*} -> aud $CORE_CLIENT, access token and introspection, not the ID token)"
        if [[ $MODE == apply ]]; then
          kcadm_write update "client-scopes/$core_scope_uuid/protocol-mappers/models/${core_mapper_line%%,*}" -r "$TARGET_REALM" \
            -b "$(audience_mapper_body "$CORE_MAPPER" "$CORE_CLIENT" "${core_mapper_line%%,*}")"
        fi
      fi
    fi
    # Keycloak keeps one link per client and scope: an optional link would block the default one.
    if [[ -n $client_uuid && -n $core_scope_uuid ]] && listed "$client_uuid" optional-client-scopes "$core_scope_uuid"; then
      change "detach $CORE_SCOPE from the optional scopes of $CLIENT_ID (it must be a default scope)"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "clients/$client_uuid/optional-client-scopes/$core_scope_uuid" -r "$TARGET_REALM"
      fi
    fi
    if [[ -n $client_uuid && -n $core_scope_uuid && ${default_scope_by_name[$CORE_SCOPE]:-} == "$core_scope_uuid" ]]; then
      log "$CLIENT_ID: default scope $CORE_SCOPE attached"
    else
      change "attach $CORE_SCOPE as a default scope of $CLIENT_ID"
      if [[ $MODE == apply ]]; then
        kcadm_write update "clients/$client_uuid/default-client-scopes/$core_scope_uuid" -r "$TARGET_REALM" -n -b '{}'
      fi
    fi
  fi
fi

# --- 5. groups as full paths ----------------------------------------------------------------------
# realm_groups_scope: the id of the realm scope "groups" when it only carries full-path Group
# Membership mappers into the access token (the production shape); empty otherwise.
realm_groups_scope() {
  local id lines line
  id=$(scope_ids "$GROUPS_SCOPE")
  [[ -n $id && $id != *$'\n'* ]] || return 0
  [[ $(csv "client-scopes/$id" protocol) == openid-connect ]] || return 0
  lines=$(csv "client-scopes/$id/protocol-mappers/models" "$MAPPER_FIELDS")
  [[ -n $lines ]] || return 0
  while IFS= read -r line; do
    line=${line#*,}
    [[ $(groups_kind "${line%,*}") == good ]] || return 0
  done <<<"$lines"
  printf '%s\n' "$id"
}
if [[ ${#bad_groups[@]} -gt 0 ]]; then
  problem "$CLIENT_ID: the claim $GROUPS_CLAIM reaches the access token differently from what inscribed reads (${bad_groups[*]}); not changed. Fix it by hand"
fi
if [[ -n $own_groups_line ]]; then
  own_rest=${own_groups_line#*,}
  if own_groups_ok "${own_rest%,*}"; then
    log "$CLIENT_ID: mapper $GROUPS_MAPPER unchanged ($GROUPS_CLAIM, full path)"
  else
    change "repair mapper $GROUPS_MAPPER on $CLIENT_ID (${own_rest%,*} -> Group Membership, claim $GROUPS_CLAIM, full path, access token and introspection)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid/protocol-mappers/models/${own_groups_line%%,*}" -r "$TARGET_REALM" \
        -b "$(groups_mapper_body "${own_groups_line%%,*}")"
    fi
  fi
  [[ ${#good_groups[@]} -eq 0 ]] || log "$CLIENT_ID: $GROUPS_CLAIM (full path) also comes from ${good_groups[*]}"
elif [[ ${#good_groups[@]} -gt 0 ]]; then
  log "$CLIENT_ID: $GROUPS_CLAIM (full path) comes from ${good_groups[*]}"
elif [[ ${#bad_groups[@]} -eq 0 ]]; then
  groups_scope_uuid=$(realm_groups_scope)
  if [[ -n $groups_scope_uuid ]]; then
    if [[ -n $client_uuid ]] && listed "$client_uuid" optional-client-scopes "$groups_scope_uuid"; then
      change "detach the realm scope $GROUPS_SCOPE from the optional scopes of $CLIENT_ID"
      if [[ $MODE == apply ]]; then
        kcadm_write delete "clients/$client_uuid/optional-client-scopes/$groups_scope_uuid" -r "$TARGET_REALM"
      fi
    fi
    change "attach the realm scope $GROUPS_SCOPE (full-path $GROUPS_CLAIM) as a default scope of $CLIENT_ID"
    if [[ $MODE == apply ]]; then
      kcadm_write update "clients/$client_uuid/default-client-scopes/$groups_scope_uuid" -r "$TARGET_REALM" -n -b '{}'
    fi
  else
    change "add mapper $GROUPS_MAPPER to $CLIENT_ID (Group Membership: claim $GROUPS_CLAIM, full path, access token and introspection)"
    if [[ $MODE == apply ]]; then
      kcadm_write create "clients/$client_uuid/protocol-mappers/models" -r "$TARGET_REALM" -b "$(groups_mapper_body)"
    fi
  fi
fi

# --- 6. what comes next ---------------------------------------------------------------------------
if [[ -n $client_uuid ]]; then
  sa_name=$(csv "clients/$client_uuid/service-account-user" username 2>/dev/null || true)
  [[ -z $sa_name ]] || log "$CLIENT_ID: service account $sa_name (its CMS roles: inscribed-cms-roles.sh)"
fi
log "next: KEYCLOAK_REALM=$TARGET_REALM inscribed-cms-roles.sh --client $CLIENT_ID --apply (CMS roles, roles claim, service account grants)"

if [[ $MODE == apply ]]; then
  log "applied $changes change(s), $warnings warning(s), $problems problem(s)"
else
  log "check: $changes change(s) pending, $warnings warning(s), $problems problem(s)"
fi
if [[ $problems != 0 ]]; then
  log "$problems problem(s) need a manual decision (see PROBLEM lines above)"
  exit 1
fi
