#!/usr/bin/env bash
# Idempotent provisioning of the event sites' Site clients (ADR-0056, addendum of 2026-10-03:
# event sites are CMS tenants too) in the production realm (e-skylab) or the sandbox realm
# (e-skylab-sandbox). One client per site, made by this script and owned by it:
#   frontend-artlab     https://artlab.yildizskylab.com      (sandbox https://sandbox-artlab.yildizskylab.com)
#   frontend-yildizjam  https://yildizjam.yildizskylab.com   (sandbox https://sandbox-yildizjam.yildizskylab.com)
#   frontend-skydays    https://skydays.yildizskylab.com     (sandbox https://sandbox-skydays.yildizskylab.com)
# Every client is
#   - confidential (the client secret is generated by Keycloak and never printed), standard flow on
#     (NextAuth's Keycloak provider, which sends PKCE), PKCE S256 required, implicit flow and direct
#     grants off, service account on (the site reads content and pushes its page manifest with
#     client_credentials; its CMS grants are content:read + schema:sync, made by
#     inscribed-cms-roles.sh), fullScopeAllowed=false (a token for one site never carries another
#     site's roles, so another site's cms:access cannot open this site's editor), consent off;
#   - redirect URI exactly https://<site>/api/auth/callback/keycloak, web origin https://<site>,
#     post-logout redirect https://<site>/*. No localhost, in either realm (decision D4: local
#     development reads the sandbox CMS without a token). Any other URI on the client is removed
#     and listed;
#   - aud skycms through the shared realm scope skycms-audience (one Audience mapper, access token
#     and introspection only), attached as a default scope; the scope is made when missing;
#   - aud core through its own scope frontend-<site>-core-audience (the shape the reconciler gives
#     frontend-main and frontend-arge: config/frontend-arge-core-audience-mappers.json), attached as
#     a default scope; the site's image bridge uploads to core /v1/media with the editor's token.
#     Without a core client in the realm it is skipped with a NOTE;
#   - groups as full paths in the access token (inscribed's collection rules read them): an
#     existing full-path Group Membership mapper reaching the access token is enough; otherwise the
#     realm scope "groups" is attached when it only carries such mappers, else the client mapper
#     groups is added. A default or optional scope that writes the claim groups differently (for
#     example microprofile-jwt, which writes realm roles into groups) is detached from this client
#     only; the realm scope and every other client keep it. Such a mapper on the client itself is
#     a PROBLEM and is never changed.
# The hand-made clients frontend-main and frontend-arge are only reported (flags, URIs, whether
# skycms reaches their access token); this script never writes them.
#
# The CMS roles (content:read, content:write, schema:sync, cms:access, client:admin), the flat
# roles claim and the service account's grants are NOT made here: config/inscribed-cms-roles.sh
# makes them, run after this script with --client frontend-<site>. Group grants are made by
# config/site-editor-grants.sh. This script never grants a role to anyone.
#
# It refuses every realm but e-skylab and e-skylab-sandbox, before it logs in; KEYCLOAK_REALM has
# no default, so production is only written when it is named. It needs the realm and its skycms
# client; without them it stops and writes nothing.
#
# Usage (inside the Keycloak image, as an operator):
#   KEYCLOAK_REALM=<realm> site-clients.sh --admin-user <admin>            # --check (default)
#   KEYCLOAK_REALM=<realm> site-clients.sh --admin-user <admin> --apply    # creates and repairs
#   KEYCLOAK_REALM=<realm> site-clients.sh --kcadm-config <file> [--apply] # reuse a kcadm session
#   ... [--site artlab|yildizjam|skydays]...                                # default: all three
#
# The administrator password is typed into kcadm's own prompt and never passes through this
# script. --kcadm-config reuses a kcadm config file an operator (or a wizard) already logged in
# with; the script then never logs in and never deletes that file. Environment: KEYCLOAK_ADMIN_URL
# (default http://keycloak:8080), KEYCLOAK_REALM (required: e-skylab or e-skylab-sandbox),
# KEYCLOAK_ADMIN_REALM (default master), KEYCLOAK_SITE_CLIENTS_ADMIN_USERNAME (or --admin-user).
#
# Output: one "[site-clients] ..." line per fact, change ("would ..." in --check), NOTE, WARNING
# and PROBLEM, then "check: N change(s) pending, W warning(s), P problem(s)" or "applied N
# change(s), ...". Exit 0 unless a PROBLEM or a missing prerequisite (1) or a usage error or a
# refused realm (2). No secret is ever read or printed.
# Operators: ops/wizards/site-cms-setup-wizard.sh in sky_lab_genel runs it, then moves the client
# secret into OpenBao (kv/<side>/<site appName>/KEYCLOAK_CLIENT_SECRET).
set -Eeuo pipefail
shopt -s inherit_errexit

umask 077

KCADM=${KCADM_BIN:-/opt/keycloak/bin/kcadm.sh}
ADMIN_URL=${KEYCLOAK_ADMIN_URL:-http://keycloak:8080}
ADMIN_REALM=${KEYCLOAK_ADMIN_REALM:-master}
PRODUCTION_REALM=e-skylab
SANDBOX_REALM=e-skylab-sandbox
TARGET_REALM=${KEYCLOAK_REALM:-}
ADMIN_USER=${KEYCLOAK_SITE_CLIENTS_ADMIN_USERNAME:-}
KCADM_CONFIG=''
OWN_CONFIG=false
MODE=check
SITES=()

ALL_SITES=(artlab yildizjam skydays)
HAND_MADE_CLIENTS=(frontend-main frontend-arge)
FLAG_FIELDS='enabled,protocol,publicClient,bearerOnly,clientAuthenticatorType,standardFlowEnabled,implicitFlowEnabled,directAccessGrantsEnabled,serviceAccountsEnabled,fullScopeAllowed,consentRequired,attributes(pkce.code.challenge.method)'
FLAG_VALUES='true,openid-connect,false,false,client-secret,true,false,false,true,false,false,S256'
FLAG_SETTINGS=(
  -s enabled=true
  -s protocol=openid-connect
  -s publicClient=false
  -s bearerOnly=false
  -s clientAuthenticatorType=client-secret
  -s standardFlowEnabled=true
  -s implicitFlowEnabled=false
  -s directAccessGrantsEnabled=false
  -s serviceAccountsEnabled=true
  -s fullScopeAllowed=false
  -s consentRequired=false
  -s 'attributes."pkce.code.challenge.method"=S256'
)
RESOURCE_CLIENT=skycms
CORE_CLIENT=core
SKYCMS_SCOPE=skycms-audience
SKYCMS_MAPPER=skycms-audience
CORE_MAPPER=core-audience
GROUPS_CLAIM=groups
GROUPS_SCOPE=groups
GROUPS_MAPPER=groups
# Mapper CSV: the free-text name last, so a comma in it cannot shift the other columns.
MAPPER_FIELDS='id,protocolMapper,config(claim.name,full.path,included.client.audience,access.token.claim,id.token.claim,introspection.token.claim),name'

usage() {
  printf 'usage: KEYCLOAK_REALM=(e-skylab|e-skylab-sandbox) %s (--admin-user <administrator> | --kcadm-config <file>) [--check | --apply] [--site artlab|yildizjam|skydays]...\n' \
    "${BASH_SOURCE[0]##*/}" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --admin-user)
      [[ $# -ge 2 ]] || usage
      ADMIN_USER=$2
      shift 2
      ;;
    --kcadm-config)
      [[ $# -ge 2 ]] || usage
      KCADM_CONFIG=$2
      shift 2
      ;;
    --site)
      [[ $# -ge 2 ]] || usage
      case $2 in
        artlab | yildizjam | skydays) SITES+=("$2") ;;
        *) printf 'unknown site %s (artlab, yildizjam or skydays)\n' "$2" >&2; exit 2 ;;
      esac
      shift 2
      ;;
    --apply)
      MODE=apply
      shift
      ;;
    --check | --dry-run)
      MODE=check
      shift
      ;;
    *)
      usage
      ;;
  esac
done
[[ ${#SITES[@]} -gt 0 ]] || SITES=("${ALL_SITES[@]}")

# Before anything else, and before a login: only the two club realms, and only when named.
if [[ $TARGET_REALM != "$PRODUCTION_REALM" && $TARGET_REALM != "$SANDBOX_REALM" ]]; then
  printf '[site-clients] refusing realm %s: set KEYCLOAK_REALM to e-skylab (production) or e-skylab-sandbox; nothing was read or changed\n' \
    "${TARGET_REALM:-(unset)}" >&2
  exit 2
fi

# site_origin SITE: the site's https origin in the target realm.
site_origin() {
  if [[ $TARGET_REALM == "$SANDBOX_REALM" ]]; then
    printf 'https://sandbox-%s.yildizskylab.com' "$1"
  else
    printf 'https://%s.yildizskylab.com' "$1"
  fi
}
site_name() {
  case $1 in
    artlab) printf 'ARTLAB' ;;
    yildizjam) printf 'YıldızJam' ;;
    skydays) printf 'SkyDays' ;;
  esac
}

if [[ -z $KCADM_CONFIG ]]; then
  if [[ -z $ADMIN_USER ]]; then
    if [[ -t 0 ]]; then
      read -r -p "Keycloak administrator username: " ADMIN_USER
    fi
    [[ -n $ADMIN_USER ]] || usage
  fi
  KCADM_CONFIG=$(mktemp /tmp/site-clients-kcadm.XXXXXX)
  OWN_CONFIG=true
elif [[ ! -r $KCADM_CONFIG ]]; then
  printf 'kcadm config %s is not readable\n' "$KCADM_CONFIG" >&2
  exit 2
fi

cleanup() {
  if [[ $OWN_CONFIG == true ]]; then
    rm -f "$KCADM_CONFIG"
  fi
}
trap cleanup EXIT

log() {
  printf '[site-clients] %s\n' "$1"
}

changes=0
warnings=0
problems=0

# change "what": counts one change and prints it; --check prints "would what".
change() {
  changes=$((changes + 1))
  if [[ $MODE == apply ]]; then
    log "$1"
  else
    log "would $1"
  fi
}

warning() {
  warnings=$((warnings + 1))
  log "WARNING: $1"
}

problem() {
  problems=$((problems + 1))
  log "PROBLEM: $1"
}

kcadm() {
  local command=$1
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

kcadm_write() {
  local stderr_file status
  stderr_file=$(mktemp /tmp/site-clients-stderr.XXXXXX)
  if kcadm "$@" >/dev/null 2>"$stderr_file"; then
    status=0
  else
    status=$?
    cat "$stderr_file" >&2
  fi
  rm -f "$stderr_file"
  return "$status"
}

# csv PATH FIELDS [kcadm arguments]: the CSV lines of a GET in the target realm (no quotes,
# empty lines dropped).
csv() {
  kcadm get "$1" -r "$TARGET_REALM" --fields "$2" --format csv --noquotes "${@:3}" | tr -d '\r' | sed '/^$/d'
}

# json_strings ITEM...: a JSON array of plain strings (URIs; a quote or backslash is refused).
json_strings() {
  local out='' item
  for item in "$@"; do
    [[ $item != *[\"\\]* ]] || { printf 'refusing to write the value %s\n' "$item" >&2; exit 1; }
    out+="${out:+,}\"$item\""
  done
  printf '[%s]' "$out"
}

# uuid_by CLIENT_ID: the id of the client with exactly this clientId (empty when absent).
uuid_by() {
  csv clients id,clientId -q "clientId=$1" | while IFS=, read -r id client_id; do
    if [[ $client_id == "$1" ]]; then printf '%s\n' "$id"; fi
  done
}

# scope_ids NAME: the ids of the client scopes with exactly this name, one per line.
scope_ids() {
  csv client-scopes id,name | while IFS=, read -r id name; do
    if [[ $name == "$1" ]]; then printf '%s\n' "$id"; fi
  done
}

# listed CLIENT_UUID PATH ID: whether ID is among the ids a client's scope list returns (grep reads
# the whole list: an early exit would make kcadm's pipe fail under pipefail).
listed() {
  csv "clients/$1/$2" id | grep -Fx "$3" >/dev/null
}

audience_mapper_body() { # audience_mapper_body NAME AUDIENCE [ID]
  local id_field=''
  [[ -z ${3:-} ]] || id_field="\"id\":\"$3\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-audience-mapper","consentRequired":false,"config":{"included.client.audience":"%s","id.token.claim":"false","access.token.claim":"true","introspection.token.claim":"true"}}' \
    "$id_field" "$1" "$2"
}

groups_mapper_body() { # groups_mapper_body [ID]
  local id_field=''
  [[ -z ${1:-} ]] || id_field="\"id\":\"$1\","
  printf '{%s"name":"%s","protocol":"openid-connect","protocolMapper":"oidc-group-membership-mapper","consentRequired":false,"config":{"claim.name":"%s","full.path":"true","multivalued":"true","access.token.claim":"true","id.token.claim":"false","userinfo.token.claim":"false","introspection.token.claim":"true","lightweight.claim":"false"}}' \
    "$id_field" "$GROUPS_MAPPER" "$GROUPS_CLAIM"
}

# An audience scope's body: not in the token's scope parameter, not on a consent screen (the
# reconciler's ensure_client_scope shape).
scope_body() {
  printf '{"name":"%s","protocol":"openid-connect","attributes":{"include.in.token.scope":"false","display.on.consent.screen":"false"}}' "$1"
}

# Mapper CSV columns after id: type, claim, full path, audience, access, id token, introspection.
# is_audience_to LINE AUDIENCE: the mapper puts AUDIENCE into the access token's aud.
is_audience_to() {
  local type claim full audience access rest
  IFS=, read -r type claim full audience access rest <<<"$1"
  [[ $type == oidc-audience-mapper && $audience == "$2" && $access == true ]]
}
# own_audience_ok LINE AUDIENCE: exactly the shape audience_mapper_body writes.
own_audience_ok() {
  local type claim full audience access id_token introspection
  IFS=, read -r type claim full audience access id_token introspection <<<"$1"
  [[ $type == oidc-audience-mapper && $audience == "$2" && $access == true && $id_token == false && $introspection == true ]]
}
# groups_kind LINE: none (does not write groups into the access token), good (full path) or bad.
groups_kind() {
  local type claim full audience access rest
  IFS=, read -r type claim full audience access rest <<<"$1"
  if [[ $claim != "$GROUPS_CLAIM" && $claim != "$GROUPS_CLAIM".* ]] || [[ $access != true ]]; then
    printf 'none'
  elif [[ $type == oidc-group-membership-mapper && $claim == "$GROUPS_CLAIM" && $full == true ]]; then
    printf 'good'
  else
    printf 'bad'
  fi
}
own_groups_ok() {
  local type claim full audience access id_token introspection
  IFS=, read -r type claim full audience access id_token introspection <<<"$1"
  [[ $type == oidc-group-membership-mapper && $claim == "$GROUPS_CLAIM" && $full == true && $access == true && $introspection == true ]]
}
# mapper_rest LINE: the CSV columns between the id and the name.
mapper_rest() {
  local rest=${1#*,}
  printf '%s' "${rest%,*}"
}

# realm_groups_scope: the id of the realm scope "groups" when it only carries full-path Group
# Membership mappers into the access token (the production shape); empty otherwise.
realm_groups_scope() {
  local id lines line
  id=$(scope_ids "$GROUPS_SCOPE")
  [[ -n $id && $id != *$'\n'* ]] || return 0
  [[ $(csv "client-scopes/$id" protocol) == openid-connect ]] || return 0
  lines=$(csv "client-scopes/$id/protocol-mappers/models" "$MAPPER_FIELDS")
  [[ -n $lines ]] || return 0
  while IFS= read -r line; do
    [[ $(groups_kind "$(mapper_rest "$line")") == good ]] || return 0
  done <<<"$lines"
  printf '%s\n' "$id"
}

# ensure_audience_scope NAME AUDIENCE MAPPER: one realm scope NAME carrying exactly one Audience
# mapper MAPPER to AUDIENCE. Sets SCOPE_ID (empty while --check plans to create it); a duplicate
# is a PROBLEM (returns 1). Not run in a subshell: its changes and problems are counted.
SCOPE_ID=''
ensure_audience_scope() {
  local name=$1 audience=$2 mapper=$3 list count id='' shape line mapper_line=''
  SCOPE_ID=''
  list=$(scope_ids "$name")
  count=$(sed '/^$/d' <<<"$list" | wc -l | tr -d ' ')
  if [[ $count -gt 1 ]]; then
    problem "$count client scopes are named $name; keep one by hand (Admin Console -> Client scopes)"
    return 1
  fi
  if [[ $count == 0 ]]; then
    change "create client scope $name (include.in.token.scope=false, display.on.consent.screen=false)"
    if [[ $MODE == apply ]]; then
      id=$(kcadm create client-scopes -r "$TARGET_REALM" -i -b "$(scope_body "$name")" | tr -d '\r')
      [[ -n $id ]] || { printf 'client scope %s was not created\n' "$name"; exit 1; }
    fi
  else
    id=$list
    shape=$(csv "client-scopes/$id" 'protocol,attributes(include.in.token.scope,display.on.consent.screen)')
    if [[ $shape == 'openid-connect,false,false' ]]; then
      log "client scope $name: attributes unchanged"
    else
      change "update client scope $name (protocol,include.in.token.scope,display.on.consent.screen: $shape -> openid-connect,false,false)"
      if [[ $MODE == apply ]]; then
        kcadm_write update "client-scopes/$id" -r "$TARGET_REALM" -s protocol=openid-connect \
          -s 'attributes."include.in.token.scope"=false' -s 'attributes."display.on.consent.screen"=false'
      fi
    fi
  fi
  if [[ -n $id ]]; then
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      if [[ ${line##*,} == "$mapper" && -z $mapper_line ]]; then
        mapper_line=$line
      else
        problem "client scope $name also has the mapper ${line##*,}; it should carry only $mapper. Remove it by hand"
      fi
    done < <(csv "client-scopes/$id/protocol-mappers/models" "$MAPPER_FIELDS")
  fi
  if [[ -z $mapper_line ]]; then
    change "add mapper $mapper to $name (aud += $audience; access token and introspection, not the ID token)"
    if [[ $MODE == apply ]]; then
      kcadm_write create "client-scopes/$id/protocol-mappers/models" -r "$TARGET_REALM" \
        -b "$(audience_mapper_body "$mapper" "$audience")"
    fi
  elif own_audience_ok "$(mapper_rest "$mapper_line")" "$audience"; then
    log "client scope $name: mapper $mapper unchanged"
  else
    change "repair mapper $mapper in $name ($(mapper_rest "$mapper_line") -> aud $audience, access token and introspection, not the ID token)"
    if [[ $MODE == apply ]]; then
      kcadm_write update "client-scopes/$id/protocol-mappers/models/${mapper_line%%,*}" -r "$TARGET_REALM" \
        -b "$(audience_mapper_body "$mapper" "$audience" "${mapper_line%%,*}")"
    fi
  fi
  SCOPE_ID=$id
}

# attach_default CLIENT_ID CLIENT_UUID SCOPE_NAME SCOPE_UUID: SCOPE becomes a default scope of the
# client (an optional link would block the default one: it is moved).
attach_default() {
  local client=$1 uuid=$2 name=$3 scope=$4
  if [[ -n $uuid && -n $scope ]] && listed "$uuid" default-client-scopes "$scope"; then
    log "$client: default scope $name attached"
    return 0
  fi
  if [[ -n $uuid && -n $scope ]] && listed "$uuid" optional-client-scopes "$scope"; then
    change "detach $name from the optional scopes of $client (it must be a default scope)"
    if [[ $MODE == apply ]]; then
      kcadm_write delete "clients/$uuid/optional-client-scopes/$scope" -r "$TARGET_REALM"
    fi
  fi
  change "attach $name as a default scope of $client"
  if [[ $MODE == apply ]]; then
    kcadm_write update "clients/$uuid/default-client-scopes/$scope" -r "$TARGET_REALM" -n -b '{}'
  fi
}

# ensure_uris CLIENT UUID FIELD WANTED LABEL: the client's list FIELD is exactly [WANTED]; other
# entries are removed and listed (the script owns these clients).
ensure_uris() {
  local client=$1 uuid=$2 field=$3 wanted=$4 label=$5 items=() item extras='' present=false
  while IFS= read -r item; do
    if [[ -n $item ]]; then items+=("$item"); fi
  done < <(csv "clients/$uuid" "$field" | tr ',' '\n')
  for item in "${items[@]}"; do
    if [[ $item == "$wanted" ]]; then present=true; else extras+="${extras:+ }$item"; fi
  done
  if [[ $present == true && -z $extras ]]; then
    log "$client: $label exactly $wanted"
    return 0
  fi
  change "set the ${label}s of $client to exactly $wanted${extras:+ (removing $extras)}"
  if [[ $MODE == apply ]]; then
    kcadm_write update "clients/$uuid" -r "$TARGET_REALM" -s "$field=$(json_strings "$wanted")"
  fi
}

credential_arguments=(
  --config "$KCADM_CONFIG"
  --server "$ADMIN_URL"
  --realm "$ADMIN_REALM"
  --user "$ADMIN_USER"
)
if [[ $OWN_CONFIG == true ]]; then
  # No redirection: kcadm asks for the password only when stdout is a terminal ("Console is not
  # active" otherwise). Its "Logging into" line goes to stderr, so stdout stays clean either way.
  "$KCADM" config credentials "${credential_arguments[@]}"
fi
site_clients=''
for site in "${SITES[@]}"; do site_clients+="${site_clients:+ }frontend-$site"; done
log "realm=$TARGET_REALM mode=$MODE clients=$site_clients"

# --- prerequisites: nothing is written unless they hold ------------------------------------------
if ! realm_name=$(kcadm get "realms/$TARGET_REALM" --fields realm --format csv --noquotes 2>/dev/null | tr -d '\r') \
  || [[ $realm_name != "$TARGET_REALM" ]]; then
  printf '[site-clients] realm %s does not exist or cannot be read; nothing was changed\n' "$TARGET_REALM" >&2
  exit 1
fi
if [[ -z $(uuid_by "$RESOURCE_CLIENT") ]]; then
  printf '[site-clients] the %s client (inscribed'"'"'s audience) does not exist in realm %s; nothing was changed\n' \
    "$RESOURCE_CLIENT" "$TARGET_REALM" >&2
  exit 1
fi
core_uuid=$(uuid_by "$CORE_CLIENT")

# --- the shared skycms audience scope -------------------------------------------------------------
skycms_scope_uuid=''
skycms_scope_ok=true
ensure_audience_scope "$SKYCMS_SCOPE" "$RESOURCE_CLIENT" "$SKYCMS_MAPPER" || skycms_scope_ok=false
skycms_scope_uuid=$SCOPE_ID

# --- one site client --------------------------------------------------------------------------
ensure_site() {
  local site=$1 client origin callback post_logout uuid created=false live_flags post_logout_live
  local core_scope core_scope_uuid core_ok sa_name line name rest kind scope_name scope_id
  local -A default_scopes=() optional_scopes=()
  local good=() bad_client=() own_groups_line=''
  client="frontend-$site"
  origin=$(site_origin "$site")
  callback="$origin/api/auth/callback/keycloak"
  post_logout="$origin/*"
  core_scope="$client-core-audience"

  # 1. the client and its flags and URIs
  uuid=$(uuid_by "$client")
  if [[ -z $uuid ]]; then
    change "create confidential client $client (standard flow with PKCE S256 and service account on, implicit and direct grants off, fullScopeAllowed=false; redirect $callback, web origin $origin, post-logout $post_logout; the secret is generated by Keycloak and never printed)"
    if [[ $MODE == apply ]]; then
      uuid=$(kcadm create clients -r "$TARGET_REALM" -i \
        -s "clientId=$client" \
        -s "name=$(site_name "$site")" \
        -s "description=${origin#https://}: NextAuth login and server-side CMS reads (Site client, ADR-0056). Made by config/site-clients.sh" \
        "${FLAG_SETTINGS[@]}" \
        -s "redirectUris=$(json_strings "$callback")" \
        -s "webOrigins=$(json_strings "$origin")" \
        -s "attributes.\"post.logout.redirect.uris\"=$post_logout" | tr -d '\r')
      [[ -n $uuid ]] || { printf 'client %s was not created\n' "$client" >&2; exit 1; }
      created=true
    fi
  else
    live_flags=$(csv "clients/$uuid" "$FLAG_FIELDS")
    if [[ $live_flags == "$FLAG_VALUES" ]]; then
      log "$client: flags unchanged ($FLAG_FIELDS=$live_flags)"
    else
      change "update $client flags ($FLAG_FIELDS: $live_flags -> $FLAG_VALUES)"
      if [[ $MODE == apply ]]; then
        kcadm_write update "clients/$uuid" -r "$TARGET_REALM" "${FLAG_SETTINGS[@]}"
      fi
    fi
    ensure_uris "$client" "$uuid" redirectUris "$callback" 'redirect URI'
    ensure_uris "$client" "$uuid" webOrigins "$origin" 'web origin'
    post_logout_live=$(csv "clients/$uuid" 'attributes(post.logout.redirect.uris)')
    if [[ $post_logout_live == "$post_logout" ]]; then
      log "$client: post-logout redirect exactly $post_logout"
    else
      change "set the post-logout redirects of $client to exactly $post_logout${post_logout_live:+ (was ${post_logout_live//##/ })}"
      if [[ $MODE == apply ]]; then
        kcadm_write update "clients/$uuid" -r "$TARGET_REALM" -s "attributes.\"post.logout.redirect.uris\"=$post_logout"
      fi
    fi
  fi
  [[ $created == false ]] || log "$client: created (id $uuid; the secret is never printed)"

  # 2. what reaches the access token: the client's mappers and its default and optional scopes.
  # A client still to be made (--check) would get the realm's default and optional scopes.
  if [[ -n $uuid ]]; then
    while IFS=, read -r scope_id scope_name; do
      if [[ -n $scope_id ]]; then default_scopes[$scope_name]=$scope_id; fi
    done < <(csv "clients/$uuid/default-client-scopes" id,name)
    while IFS=, read -r scope_id scope_name; do
      if [[ -n $scope_id ]]; then optional_scopes[$scope_name]=$scope_id; fi
    done < <(csv "clients/$uuid/optional-client-scopes" id,name)
  else
    while IFS=, read -r scope_id scope_name rest; do
      if [[ -n $scope_id && $rest == openid-connect ]]; then default_scopes[$scope_name]=$scope_id; fi
    done < <(csv default-default-client-scopes id,name,protocol)
    while IFS=, read -r scope_id scope_name rest; do
      if [[ -n $scope_id && $rest == openid-connect ]]; then optional_scopes[$scope_name]=$scope_id; fi
    done < <(csv default-optional-client-scopes id,name,protocol)
  fi

  # 3. aud skycms: the shared scope
  if [[ $skycms_scope_ok == true ]]; then
    attach_default "$client" "$uuid" "$SKYCMS_SCOPE" "$skycms_scope_uuid"
  fi

  # 4. aud core: the site's own scope
  if [[ -z $core_uuid ]]; then
    log "NOTE: realm $TARGET_REALM has no $CORE_CLIENT client; $core_scope skipped (rerun once core's client exists)"
  else
    core_ok=true
    ensure_audience_scope "$core_scope" "$CORE_CLIENT" "$CORE_MAPPER" || core_ok=false
    core_scope_uuid=$SCOPE_ID
    if [[ $core_ok == true ]]; then
      attach_default "$client" "$uuid" "$core_scope" "$core_scope_uuid"
    fi
  fi

  # 5. groups as full paths; a scope writing groups differently is detached from this client
  if [[ -n $uuid ]]; then
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      name=${line##*,}
      rest=$(mapper_rest "$line")
      if [[ $name == "$GROUPS_MAPPER" && ${rest%%,*} == oidc-group-membership-mapper ]]; then
        own_groups_line=$line
        continue
      fi
      case $(groups_kind "$rest") in
        good) good+=("client mapper $name") ;;
        bad) bad_client+=("client mapper $name") ;;
      esac
    done < <(csv "clients/$uuid/protocol-mappers/models" "$MAPPER_FIELDS")
  fi
  for kind in default optional; do
    while IFS= read -r scope_name; do
      [[ -n $scope_name ]] || continue
      if [[ $kind == default ]]; then scope_id=${default_scopes[$scope_name]}; else scope_id=${optional_scopes[$scope_name]}; fi
      local scope_good=false scope_bad=false
      while IFS= read -r line; do
        [[ -n $line ]] || continue
        case $(groups_kind "$(mapper_rest "$line")") in
          good) scope_good=true ;;
          bad) scope_bad=true ;;
        esac
      done < <(csv "client-scopes/$scope_id/protocol-mappers/models" "$MAPPER_FIELDS")
      if [[ $scope_bad == true ]]; then
        change "detach the $kind scope $scope_name from $client (it writes the claim $GROUPS_CLAIM differently from what inscribed reads; the realm scope and other clients keep it)"
        if [[ $MODE == apply && -n $uuid ]]; then
          kcadm_write delete "clients/$uuid/$kind-client-scopes/$scope_id" -r "$TARGET_REALM"
        fi
      elif [[ $scope_good == true && $kind == default ]]; then
        good+=("default scope $scope_name")
      fi
    done < <(if [[ $kind == default ]]; then printf '%s\n' "${!default_scopes[@]}"; else printf '%s\n' "${!optional_scopes[@]}"; fi | sort)
  done
  if [[ ${#bad_client[@]} -gt 0 ]]; then
    problem "$client: the claim $GROUPS_CLAIM reaches the access token differently from what inscribed reads (${bad_client[*]}); not changed. Fix it by hand"
  fi
  if [[ -n $own_groups_line ]]; then
    if own_groups_ok "$(mapper_rest "$own_groups_line")"; then
      log "$client: mapper $GROUPS_MAPPER unchanged ($GROUPS_CLAIM, full path)"
    else
      change "repair mapper $GROUPS_MAPPER on $client ($(mapper_rest "$own_groups_line") -> Group Membership, claim $GROUPS_CLAIM, full path, access token and introspection)"
      if [[ $MODE == apply ]]; then
        kcadm_write update "clients/$uuid/protocol-mappers/models/${own_groups_line%%,*}" -r "$TARGET_REALM" \
          -b "$(groups_mapper_body "${own_groups_line%%,*}")"
      fi
    fi
  elif [[ ${#good[@]} -gt 0 ]]; then
    log "$client: $GROUPS_CLAIM (full path) comes from ${good[*]}"
  elif [[ ${#bad_client[@]} -eq 0 ]]; then
    local groups_scope_uuid
    groups_scope_uuid=$(realm_groups_scope)
    if [[ -n $groups_scope_uuid ]]; then
      attach_default "$client" "$uuid" "$GROUPS_SCOPE" "$groups_scope_uuid"
    else
      change "add mapper $GROUPS_MAPPER to $client (Group Membership: claim $GROUPS_CLAIM, full path, access token and introspection)"
      if [[ $MODE == apply ]]; then
        kcadm_write create "clients/$uuid/protocol-mappers/models" -r "$TARGET_REALM" -b "$(groups_mapper_body)"
      fi
    fi
  fi

  # 6. what comes next
  if [[ -n $uuid ]]; then
    sa_name=$(csv "clients/$uuid/service-account-user" username 2>/dev/null || true)
    [[ -z $sa_name ]] || log "$client: service account $sa_name (its CMS roles: inscribed-cms-roles.sh)"
  fi
  log "next: KEYCLOAK_REALM=$TARGET_REALM inscribed-cms-roles.sh --client $client --apply, then site-editor-grants.sh --site $site"
}

for site in "${SITES[@]}"; do
  ensure_site "$site"
done

# --- the hand-made clients: read-only report -------------------------------------------------------
for client in "${HAND_MADE_CLIENTS[@]}"; do
  uuid=$(uuid_by "$client")
  if [[ -z $uuid ]]; then
    log "NOTE: $client does not exist in realm $TARGET_REALM (not made here)"
    continue
  fi
  IFS=, read -r full_scope service_accounts direct_grants < <(csv "clients/$uuid" fullScopeAllowed,serviceAccountsEnabled,directAccessGrantsEnabled)
  redirects=$(csv "clients/$uuid" redirectUris | tr ',' ' ')
  skycms_from=''
  while IFS= read -r line; do
    [[ -n $line ]] || continue
    if is_audience_to "$(mapper_rest "$line")" "$RESOURCE_CLIENT"; then skycms_from+="${skycms_from:+, }client mapper ${line##*,}"; fi
  done < <(csv "clients/$uuid/protocol-mappers/models" "$MAPPER_FIELDS")
  while IFS=, read -r scope_id scope_name; do
    [[ -n $scope_id ]] || continue
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      if is_audience_to "$(mapper_rest "$line")" "$RESOURCE_CLIENT"; then skycms_from+="${skycms_from:+, }default scope $scope_name"; fi
    done < <(csv "client-scopes/$scope_id/protocol-mappers/models" "$MAPPER_FIELDS")
  done < <(csv "clients/$uuid/default-client-scopes" id,name)
  log "hand-made $client (report only, never written here): fullScopeAllowed=$full_scope serviceAccountsEnabled=$service_accounts directAccessGrantsEnabled=$direct_grants; redirect URIs: ${redirects:-none}; aud $RESOURCE_CLIENT from: ${skycms_from:-nothing}"
done

if [[ $MODE == apply ]]; then
  log "applied $changes change(s), $warnings warning(s), $problems problem(s)"
else
  log "check: $changes change(s) pending, $warnings warning(s), $problems problem(s)"
fi
if [[ $problems != 0 ]]; then
  log "$problems problem(s) need a manual decision (see PROBLEM lines above)"
  exit 1
fi
